### DISCUSSION TITLE
Solarprognose für mehrere Dachflächen

### DISCUSSION THREAD

**Discussion by ledermann** [solectrus/solectrus#2396] [Updates]
Ab sofort ist der [Forecast-Collector](https://github.com/solectrus/forecast-collector) in [Version 0.4.0](https://github.com/solectrus/forecast-collector/releases/tag/v0.4.0) verfügbar und bietet endlich auch eine Unterstützung für mehrere Dachflächen. Diese erfolgt so, dass für jede Dachfläche eine separate Prognose errechnet und die Erwartungswerte addiert werden.

Falls du SOLECTRUS nutzt und Solarmodule auf mehr als nur einer Dachfläche hast, dann gehe wie folgt vor, um eine genauere Solarprognose zu erhalten:

## Schritt 1

Bearbeite die `.env`-Datei analog diesem Beispiel:
https://github.com/solectrus/forecast-collector/blob/develop/.env.example

Die Idee ist, zunächst eine Variable `FORECAST_CONFIGURATIONS` mit der Anzahl der Dachflächen zu ergänzen und dann für jede Fläche die Parameter einzutragen, die sich unterscheiden.

Beispiel für zwei Dachflächen: 

Dach 1:
- Ausrichtung Ost (-90°)
- Neigung 30°
- Peak-Leistung: 4,5 kWp

Dach 2:
- Ausrichtung West (90°)
- Neigung 40°
- Peak-Leistung 6,9 kWp

Hier sind folgende Angaben in der `.env` erforderlich:

```env
FORECAST_LATITUDE=50.123
FORECAST_LONGITUDE=6.456
FORECAST_CONFIGURATIONS=2
FORECAST_0_AZIMUTH=-90
FORECAST_0_DECLINATION=30
FORECAST_0_KWP=4.5
FORECAST_1_AZIMUTH=90
FORECAST_1_DECLINATION=40
FORECAST_1_KWP=6.9
FORECAST_INTERVAL=900
```

Wichtig ist, das Intervall nicht zu niedrig zu setzen. Bei https://forecast.solar gibt es ein Rate-Limit von 12 Abfragen pro Stunde, wobei aus jeder Dachfläche eine separate Abfrage resultiert. Bei 2 Dachflächen sind also nur 6 Abfragen pro Stunden erlaubt, d.h. das Intervall muss mindestens 600 Sekunden (= 10 Minuten) betragen.

## Schritt 2

Ergänze die neuen Variablen in der `docker-compose.yml`, damit der Forecast-Collector Zugriff auf die neuen Variablen in der `.env` bekommt. Hierzu ein Beispiel:

```yaml
forecast-collector:
  image: ghcr.io/solectrus/forecast-collector:latest
  ...
  environment:
    ...
    - FORECAST_LATITUDE
    - FORECAST_LONGITUDE
    - FORECAST_CONFIGURATIONS
    - FORECAST_0_DECLINATION
    - FORECAST_0_AZIMUTH
    - FORECAST_0_KWP
    - FORECAST_1_DECLINATION
    - FORECAST_1_AZIMUTH
    - FORECAST_1_KWP
    - FORECAST_INTERVAL
  ...
```

## Schritt 3

Hole das aktualisierte Docker-Image und starten die Container neu:

```bash
docker compose pull
docker compose up -d
```

Danach lohnt es sich, in die Logs des Forecast-Containers zu gucken, ob auch alles glattläuft:

```
docker logs solectrus-forecast-collector-1
```

Falls dieser Befehl fehlschlägt: Möglicherweise heißt der Container nicht `solectrus-forecast-collector-1`, sondern irgendwie anders. Den genauen Namen findet man mit `docker ps` heraus.

**Comment by halmich** [comment]
Hallo Georg,
hab die Anleitung befolgt und ich glaube es funktioniert. Zumindest wird weiterhin ein Wert vorhergesagt ;-)
Sehe ich es richtig - die Variablen wie z,B, FORECAST_KWP werden nicht mehr benötigt, wenn FORECAST_0_KWP existiert und kann dann in der .env auskommentiert werden? In der docker-compose.yml kann man sie jedoch stehen lassen, oder?
Daneben: docker logs solectrus-forecast-collector-1 liefert bei mir: Error: No such container: solectrus-forecast-collector  (auf einer synology nas)

**Reply by ledermann** [reply]
Grundsätzlich: Die Variable FORECAST_X_Y überschreibt die Variable FORECAST_Y. Insofern ja, FORECAST_KWP wird nicht mehr benötigt, wenn FORECAST_0_KWP, FORECAST_1_KWP etc. vorhanden sind. Sie schaden aber auch nicht, weder in der `.env` noch in der `docker-compose.yml`.

Bezüglich Logs: Es kann sein, dass bei dir der Container anders heißt. Wie genau, bekommst du mit `docker ps` heraus.

**Comment by KippA67** [comment]
Hallo, bei mir klappt das irgendwie nicht.
Bei mir kommt immer die folgende Fehlermedung:

`pi@raspberrypi:~/solectrus $ docker compose pull
yaml: line 109: mapping values are not allowed in this context
pi@raspberrypi:~/solectrus $`

Die docker-compose.yml sieht folgendermaßen aus:

```
forecast-collector:
  image: ghcr.io/solectrus/forecast-collector:latest
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
    - FORECAST_LATITUDE
    - FORECAST_LONGITUDE
    - FORECAST_CONFIGURATIONS
    - FORECAST_0_DECLINATION
    - FORECAST_0_AZIMUTH
    - FORECAST_0_KWP
    - FORECAST_1_DECLINATION
    - FORECAST_1_AZIMUTH
    - FORECAST_1_KWP
    - FORECAST_INTERVAL
    restart: always
```

Gruß
Andreas

**Reply by ledermann** [reply]
Die Ursache ist hier ganz simpel: Die Einrückung stimmt nicht. Die unter `environment` aufgeführten Variablen müssen alle gleich eingerückt sein (zwei Spaces), sonst ist die Datei nicht valide.

**Reply by KippA67** [reply]
Besten Dank,
ist halt wie immer -> kaum macht man es richtig, dann funktioniert es ;-)
Super Support, wie immer

**Comment by halmich** [comment]
> Bezüglich Logs: Es kann sein, dass bei dir der Container anders heißt. Wie genau, bekommst du mit `docker ps` heraus.

Danke! Es war ein Unterstrich anstatt Bindestrich, also solectrus_forecast-collector-1 (y)
Läuft wunderbar.

**Comment by patricknitsch** [comment]
Hallo Georg,

echt cool, dass du mehrere Flächen auch unterstützt. Ich habe das mal nach deiner Anleitung ausprobiert. Habe 3 Flächen mit gleicher Neigung, eben nur unterschiedliche Ausrichtung und Leistung. Habe alles eingegeben und aktualisiert. Im Vergleich zum IOBroker, wo auch ein Forecast läuft, habe ich aber einen Unterschied von 40kWh.

Normalerweise addierst du ja auch nur die einzelnen Forecast zusammen, oder?

**Reply by ledermann** [reply]
Beim [ioBroker.pvforecast](https://github.com/iobroker-community-adapters/ioBroker.pvforecast#iobrokerpvforecast) lassen sich die Dachflächen per UI definieren, was zweifellos komfortabler ist. Intern dürfte aber das Gleiche passieren wie beim Forecast-Collector für SOLECTRUS: Die zu erwartenden Erträge der einzelnen Dachflächen werden summiert.

Wenn das bei dir nicht klappt, ist vermutlich etwas bei der Konfiguration schiefgegangen. Zur Erinnerung: `.env` muss erweitert werden (`FORECAST_CONFIGURATIONS=3`, dann `FORECAST_0_...` bis `FORECAST_2_...`), in der `docker-compose.yml` müssen die ergänzten Variablen bekannt gemacht werden, dann Container neu starten. Am besten prüfst du das Log des Forecast-Collectors. Wenn alles richtig gemacht wurde, sollten dort die drei Requests aufgeführt werden.

**Reply by halmich** [reply]
Greift IOBroker über die gleiche API von forecast.solar auf die Daten zu?
Ich muss die nächsten Tage mal warten, wie es sich einpendelt.
Ich habe je 9 kWp Ost/West. Bisher hatte ich 18 kWp West eingetragen und zumindest an wolkenfreien Tagen war die Vorhersage ziemlich gut. Gestern war die Vorhersage mit 9/9 um über 100% daneben, obwohl das Wetter gut vorherzusagen war. Daher mal abwarten, wie es die nächsten Tage läuft.

#92 Fetching forecast
  0: https://api.forecast.solar/estimate/4x.xx774/y.yy6958/25/-105/9.0?damping=0,0&time=seconds ... OK
  1: https://api.forecast.solar/estimate/4x.xx774/y.yy6958/25/75/9.0?damping=0,0&time=seconds ... OK
  Pushing forecast to InfluxDB ... OK
  Sleeping for 900 seconds ...

**Reply by patricknitsch** [reply]
Anscheinend ist da wirklich etwas schief gegangen. Er macht drei Abfragen, aber jeweils nur mit dem Forecast_0_ Werten.

**Reply by ledermann** [reply]
@halmich: Soweit ich den Quelltext des ioBroker-Adapters verstehe, arbeitet der im Wesentlichen genauso. Die Qualität der Vorhersage kann ich natürlich nicht beeinflussen. Bei mir liegen Erwartung und Realität auch oft weit auseinander. Es kommt täglich etwa 30% mehr Energie als von forecast.solar prognostiziert, manchmal auch über 100% mehr. Die Ursache dafür habe ich nicht herausfinden können.

@patricknitsch: Sieht nach Fehlkonfiguration aus. Bitte poste mal die relevanten Ausschnitte aus `.env` und `docker-compose.yml`.

**Reply by StevieC121176** [reply]
Wäre evtl. auch eine andere API möglich, z.Bsp. von SOLCAST? mMn. ist die genauer.

**Reply by ledermann** [reply]
@StevieC121176: Dass Solcast besser ist, wusste ich bislang nicht. Ein Issue gibt es jedenfalls schon länger: https://github.com/solectrus/forecast-collector/issues/162

**Reply by StevieC121176** [reply]
Forcast.solar hat teilweise über den Tag verteilt Sprünge von mehreren 100% drin. Mal stand 6kwh , eine halbe Stunde später zeigt er mir 55kwh an, dann wieder 24kwh. Tatsächlich waren es 38kwh an dem Tag. Solcast hat mir an dem Tag zwischen 34 und 42kwh angezeigt.
Im Hochsommer, wo es am ganzen Tag keine Wolke gab, fällt das nicht so auf. Aber die letzten 2 Monate waren bei uns doch arg von Wolken gezeichnet und da gab es kaum Vorhersagen bei forcast.solar, die auch nur annähernd am tatsächlichen Wert waren.

Was evtl. auch noch schön wäre, eine Art Abweichung, die man einstellen könnte (in %). Die Vorhersagen gehen ja immer vom optimalen Fall aus, dh. ohne Verschattung der Dachfläche. Wir haben z. Bsp. einen Baum vom Nachbarn, der uns im Sommer am Tag gute 3-5kwh kostet. So etwas könnte man dadurch bei der Vorhersage gleich mit abrechnen.

**Reply by patricknitsch** [reply]
@ledermann : Anbei die Werte aus .env

```
# Latitude of the plant location
FORECAST_LATITUDE=50.14795576880382
#
# Longitude of the plant location
FORECAST_LONGITUDE=11.257440447807314
#
# Forecast Configuration?
FORECAST_CONFIGURATIONS=3

# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_DECLINATION=20
#
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
FORECAST_AZIMUTH=10
FORECAST_0_AZIMUTH=-80
FORECAST_0_KWP=4.95
FORECAST_1_AZIMUTH=10
FORECAST_1_KWP=9.24
FORECAST_2_AZIMUTH=100
FORECAST_2_KWP=4.95
#
# Installed modules power in kilowatt peak (kWp)
FORECAST_KWP=19.14
#
# Update interval in seconds, 900s = 15 minutes, the public (and free) API allows a minimum of 900 seconds
FORECAST_INTERVAL=900
```


Werte aus docker-compose.yml:

```
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_INTERVAL
    restart: always
```

**Reply by ledermann** [reply]
@patricknitsch Es fehlt in `docker-compose.yml` ein Eintrag für `FORECAST_CONFIGURATIONS`

**Reply by patricknitsch** [reply]
Danke Georg. Den Wald vor lauter Bäumen nicht gesehen... Funktioniert jetzt. Echt super Arbeit, was du bisher in diesem Projekt geleistet hast.

**Comment by Gabinger** [comment]
Hi,
ich bekomme die Fehlermeldung 
https://api.forecast.solar/estimate/52.1937/7.9822///?damping=0,0&time=seconds    Error 400 "Bad Request"

**.env**
```
##################################################################
# Solar forecasting with https://forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate
#
FORECAST_LATITUDE=52.1937
FORECAST_LONGITUDE=7.9822
FORECAST_CONFIGURATIONS=2
FORECAST_0_AZIMUTH=65
FORECAST_0_DECLINATION=50
FORECAST_0_KWP=7.360
FORECAST_1_AZIMUTH=-25
FORECAST_1_DECLINATION=38
FORECAST_1_KWP=2.240
FORECAST_INTERVAL=900
```
`
**Docker-Compose.yml**

```
`forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_INTERVAL
    restart: always
```
`

Kann mir jemand helfen??
Grüße

**Reply by ledermann** [reply]
@Gabinger In der `docker-compose.yml` fehlt im Abschnitt `environment`: 

```
- FORECAST_CONFIGURATIONS
- FORECAST_0_AZIMUTH
- FORECAST_0_DECLINATION
- FORECAST_0_KWP
- FORECAST_1_AZIMUTH
- FORECAST_1_DECLINATION
- FORECAST_1_KWP
```

Siehe ganz oben, Schritt 2.

**Reply by Gabinger** [reply]
Okay vielen Dank, hatte glaube ich **den Überblick verloren** :( 
Und dann die fehlenden Parameter im Senec Collector eingetragen.
Nochmals danke!!
Toll Arbeit. Funktioniert jetzt alles top!!

**Comment by megalapp** [comment]
Hi, ich habe die Aufteilung gestern in die beiden Dateien eingetragen. Die Anzeige schaut mir jetzt viel valider aus. Vielen Dank 🥇

**Comment by Zeppelin-PV** [comment]
Wie wird es eigentlich seitens des Anbieters Forecast Solar gehandhabt ?
wenn ich drei Dachflächen abfrage, sind das dann drei einzelne Abfragen und erhöhen somit den Abfragezyklus von 15min ?
Die Beschreibung, so sehe ich eben, lässt das im Public Model gar nicht zu.
Ist Solectrus auch in der Lage Forecast einzubinden wenn man einen APIkey von Forecast.Solar hat ?

**Reply by ledermann** [reply]
Ja, jede Dachfläche führt zu einem eigenen API-Request. In der kostenfreien Variante von forecast.solar sind [12 Requests pro Stunde](https://doc.forecast.solar/account_models) erlaubt. Bei drei Dachflächen bedeutet dies, dass das Intervall auf mindestens 15min gestellt werden muss `((60 / 12) * 3)`. Der Collector erfordert eine Angabe in Sekunden, also `15 * 60 = 900`. Das genügt aber, öfter muss man die Vorhersage wirklich nicht abrufen.

Die kostenpflichtigen Varianten können wegen des größeren Datenhorizonts interessant sein (3 Tage oder sogar 6 Tage). Dafür braucht man einen API-Key, den man im Forecast-Collector [über eine Umgebungsvariable](https://github.com/solectrus/forecast-collector/blob/develop/.env.example#L33-L34) einstellen kann.

**Comment by Zeppelin-PV** [comment]
seltsam, mit diesen Einstellungen bekomme ich gar keine Vorschau mehr

```
##################################################################
# Solar forecasting with https://forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate
#
# Latitude of the plant location
FORECAST_LATITUDE=48.69480795933651
#
# Longitude of the plant location
FORECAST_LONGITUDE=9.736329703905348
#
# Aufteilen der PV-Anlage auf zwei Dachflächen ost/west
FORECAST_CONFIGURATIONS=3
#
# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_0_DECLINATION=24
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
FORECAST_0_AZIMUTH=-93
# Installed modules power in kilowatt peak (kWp)
FORECAST_0_KWP=8.910
#
# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_1_DECLINATION=24
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, >
FORECAST_1_AZIMUTH=87
# Installed modules power in kilowatt peak (kWp)
FORECAST_1_KWP=2.835
#
# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_2_DECLINATION=30
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, >
FORECAST_2_AZIMUTH=0
# Installed modules power in kilowatt peak (kWp)
FORECAST_2_KWP=0.820
#
# Update interval in seconds, 900s = 15 minutes, the public (and free) API allows a minimum of 900 seconds
FORECAST_INTERVAL=900
```

```
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_CONFIGURATIONS 
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_INTERVAL
    restart: always
```
