### DISCUSSION TITLE
Backupmöglichkeit influxdb

### DISCUSSION THREAD

**Discussion by StevieC121176** [solectrus/solectrus#2860] [Q&A] [answered]
seit letzter Woche ist meine SD Karte defekt und ich musste Solectrus komplett neu aufsetzen. Jetzt sind natürlich alle Daten vom letzten Jahr weg. Leider habe ich keine Möglichkeit bzw. fehlt mir das Wissen dazu, die Daten aus meinen WR in Influxdb zu übertragen. Gibt es eine Möglichkeit eines Datenbank Backups für die Solectrus DB damit ich zumindest in Zukunft die Daten ab und an sichern kann. Am besten wäre natürlich so etwas wie der Backup Adapter in iobroker, der einmal am Tag alles sichert.

**Comment by ledermann** [comment]
Sehr ärgerlich, das tut mir leid.

Ja, es gibt eine Backup-Möglichkeit, die ich auch selbst für meine eigene SOLECTRUS-Instanz nutze:
https://github.com/solectrus/influxdb2-s3-backup

Dieses Tool erfordert allerdings Amazon S3, was ich persönlich für eine gute Sache halte, weil ein Backup in die Cloud die Daten wirklich aus der Gefahrenzone bringt. Möglich wäre aber auch, mit [MinIO](https://min.io/) einen eigenen S3-Clone im lokalen Netz zu betreiben - möglicherweise ist das aber Overkill.

**Reply by StevieC121176** [reply]
Ok, soweit ich verstanden habe lege ich mir ein S3 Konto an. Dort werde ich sicherlich Zugangsdaten bekommen. 
Aus der readme zum S3 Backup werde ich aber nicht ganz schlau. Gibt es da eine Config wo ich das dann eintragen muss? Muss ich noch etwas zusätzlich installieren?
Wie gesagt, meine Kenntnisse sind in dieser Hinsicht recht dürftig.

**Reply by ledermann** [reply]
Das Backup wird als zusätzlicher Dienst in deine bestehende SOLECTRUS-Konfiguration hinzugefügt, also in die bestehende `docker-compose.yml`- bei mir selbst sieht das in etwa so aus:

```yaml
services:
  app:
    # ...
    image: ghcr.io/solectrus/solectrus:develop

  influxdb:
    # ...
    image: influxdb:2.7-alpine

  fluxbackup:
    image: ghcr.io/solectrus/influxdb2-s3-backup:latest
    environment:
      INFLUXDB_HOST: influxdb
      INFLUXDB_ORG: my-org
      INFLUXDB_TOKEN: my-super-token
      INFLUXDB_BACKUP_PORT: 8086
      S3_BUCKET: my-s3-bucket
      S3_PREFIX: influxdb_backup
      AWS_ACCESS_KEY_ID: my-aws-access-key
      AWS_SECRET_ACCESS_KEY: my-aws-secret
      CRON: '0 2 * * *'
```

Die Konfiguration erfolgt also ausschließlich über Umgebungsvariablen, eine weitere Config gibt es nicht. Es muss auch nichts zusätzlich installiert werden. Der Influx-Backup-Service läuft permanent und wird regelmäßig aktiv, in meinem Beispiel also jeden Tag um 02:00 Uhr. Der Backup-Container kommuniziert mit dem InfluxDB-Container, um an die Daten heranzukommen. Wichtig ist das korrekte Token für InfluxDB, es werden Admin-Rechte benötigt. Der S3-Bucket muss außerdem bereits vorhanden sein, also vorher manuell anlegen, was sich über das UI von AWS S3 erledigen lässt.

Wenn du noch nie etwas mit AWS zu tun hattest, dann ist das allerdings schon eine Herausforderung, AWS ist ein Monster mit unzähligen Diensten. S3 ist einer davon.
