### DISCUSSION TITLE
Solcast Vorhersage mit alter Konfiguration

### DISCUSSION THREAD

**Discussion by StevieC121176** [solectrus/solectrus#3400] [General]
Da die Forcast.Solar Vorhersage bei mir doch arg , naja sagen wir mal ungenau ist, habe ich versucht die Solcast Vorhersage in meine alte Konfiguration zu integrieren.
Bisher ohne Erfolg.
Anlage bei Solcast ist angelegt, 2 Dachflächen, API Key alles vorhanden.
Er bringt mir auch keine Fehler im Log:

```
forecast-collector-1  | Forecast collector for SOLECTRUS, Version 0.5.2, built at 2024-07-15T08:41:36.978Z
forecast-collector-1  | https://github.com/solectrus/forecast-collector
forecast-collector-1  | Copyright (c) 2020-2024 Georg Ledermann, released under the MIT License
forecast-collector-1  | 
forecast-collector-1  | Using Ruby 3.3.4 on platform aarch64-linux-musl
forecast-collector-1  | Pulling from api.solcast.com.au every 17280 seconds
forecast-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket solectrus, measurement Forecast
forecast-collector-1  | 
forecast-collector-1  | #1 Fetching forecast at 2024-08-29T10:42:19+02:00
forecast-collector-1  |   0: https://api.solcast.com.au/rooftop_sites/4dee-9da4-745e-XXXX/forecasts?format=json&api_key=O7NYyRGD0lIDS0fBXXXXXXXXXXXXX ... OK
forecast-collector-1  |   1: https://api.solcast.com.au/rooftop_sites/7822-b7a7-3706-XXXX/forecasts?format=json&api_key=O7NYyRGD0lIDS0fBXXXXXXXXXXXXX ... OK
forecast-collector-1  |   Pushing forecast to InfluxDB ... OK
forecast-collector-1  |   Sleeping for 17280 seconds (until 2024-08-29 15:30:22 +0200) ...
```

leider bekomme ich keine Anzeige in Solectrus

compose.yml:

```
forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_FORECAST}
      - TZ
      - FORECAST_PROVIDER
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_CONFIGURATIONS
      - FORECAST_0_LATITUDE
      - FORECAST_0_LONGITUDE
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_0_DAMPING_MORNING
      - FORECAST_0_DAMPING_EVENING
      - FORECAST_1_LATITUDE
      - FORECAST_1_LONGITUDE
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_1_DAMPING_MORNING
      - FORECAST_1_DAMPING_EVENING
      - FORECAST_2_LATITUDE
      - FORECAST_2_LONGITUDE
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_2_DAMPING_MORNING
      - FORECAST_2_DAMPING_EVENING
      - FORECAST_3_LATITUDE
      - FORECAST_3_LONGITUDE
      - FORECAST_3_DECLINATION
      - FORECAST_3_AZIMUTH
      - FORECAST_3_KWP
      - FORECAST_3_DAMPING_MORNING
      - FORECAST_3_DAMPING_EVENING
      - FORECAST_INTERVAL
      - FORECAST_SOLAR_APIKEY
      - FORECAST_DAMPING_MORNING
      - FORECAST_DAMPING_EVENING
      - FORECAST_HORIZON
      - FORECAST_INVERTER
      - SOLCAST_APIKEY
      - SOLCAST_SITE
      - SOLCAST_0_SITE
      - SOLCAST_1_SITE
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'
```

.env:

```
FORECAST_PROVIDER=solcast

# Number of planes (if you have more than one). Default is 1. Forecast.solar allows up to 4 planes, Solcast up to 2.
FORECAST_CONFIGURATIONS=2

# Update interval in seconds
FORECAST_INTERVAL=17280

# Measurement name for InfluxDB
FORECAST_INFLUX_MEASUREMENT=forecast



### Details for solcast.com

SOLCAST_APIKEY=O7NYyRGD0xxxxxxxxxxxxxx
SOLCAST_SITE=1111-2222-3333-4444

SOLCAST_0_SITE=4dee-9da4-745e-xxxx
SOLCAST_1_SITE=7822-b7a7-3706-xxxx
```
