### DISCUSSION TITLE
Shelly für kleinere Verbraucher integrieren

### DISCUSSION THREAD

**Discussion by ledermann** [solectrus/solectrus#3411] [General]
Von @Zeppelin-PV in [#3396](https://github.com/solectrus/solectrus/issues/3396#issuecomment-2324901633). Hierher verschoben, weil es im Issue um die Implementierung gehen soll, nicht um Installationsfragen:

>... habe fertig !
> Shelly Pro 1pm für Aufzug installiert, und Shelly Plug S für die Gastherme. Kann ich jetzt schon die beiden Geräte vorbereiten für die Option "zusätzlicher Verbraucher"? MQTT muß aktiviert werden- logisch, aber was muss da alles eingetragen werden damit Solectrus die Daten empfangen kann ?

Ja, du kannst das schon vorbereiten. Ich gehe davon aus, dass die beiden Shellys im lokalen Netz über ihre IP erreichbar sind, d.h. die Website der Geräte lassen sich im Browser aufrufen.

Wenn du noch keinen MQTT-Broker im Betrieb hast (was ich vermute), würde ich MQTT eher meiden, das macht alles komplizierter. Nimm stattdessen den [Shelly-Collector](https://github.com/solectrus/shelly-collector), für jeden deiner beiden Shellys einen eigenen. Das sind dann zwei zusätzliche Services in deiner Compose-Datei.

**Comment by ledermann** [comment]
So in etwa sollte das funktionieren:

```yaml
shelly-collector-aufzug:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT=Aufzug
    - SHELLY_HOST=192.168.123.45
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped

shelly-collector-therme:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT=Therme
    - SHELLY_HOST=192.168.123.46
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
```

Diese Zeilen in deine bestehende compose-Datei einfügen (Einrückung beachten!), IP-Adressen anpassen, dann `docker compose up -d`. Fertig. Unbedingt Log prüfen, ob etwas schiefläuft.

In SOLECTRUS wirst du danach natürlich noch nichts sehen. Aber die Messwerte werden in der InfluxDB schon mal gesammelt.

**Reply by Zeppelin-PV** [reply]
der Shelly-Collector muss doch auch sicherlich in der .env stehen - oder ?

**Reply by ledermann** [reply]
Nicht unbedingt, ich habe die Werte (IP und Measurement) direkt in die Compose geschrieben (die Angaben hinter dem `=`).

Aber du kannst es auch so machen, das ist natürlich sauberer, weil die Variablen dann nur in der `.env` stehen.

`compose.yaml`

```yaml
shelly-collector-aufzug:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT={SHELLY_MEASUREMENT_AUFZUG}
    - SHELLY_HOST=${SHELLY_HOST_AUFZUG}
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped

shelly-collector-therme:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT={SHELLY_MEASUREMENT_THERME}
    - SHELLY_HOST=${SHELLY_HOST_THERME}
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
```

`.env`

```env
SHELLY_INTERVAL=5
SHELLY_HOST_THERME=192.168.123.46
SHELLY_HOST_AUFZUG=192.168.123.45
SHELLY_MEASUREMENT_THERME=Therme
SHELLY_MEASUREMENT_AUFZUG=Aufzug
```

**Reply by Zeppelin-PV** [reply]
soweit, so gut, habe alles wie beschrieben eingetragen, und es scheint auch zu laufen, ohne Fehler
hier habe ich das Log vom Senec-Collector mit einem seltsamen Hinweis
der Log vom Shelly-Collector ist nicht da bzw. die Meldung "no such service: shelly-collector"

```
admin@raspberrypi:/home/pi/solectrus $ docker compose logs senec-collector
senec-collector-1  | /usr/local/bundle/gems/influxdb-client-3.1.0/lib/influxdb2/client/flux_csv_parser.rb:21: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of influxdb-client-3.1.0 to add base64 into its gemspec.
senec-collector-1  | SENEC collector for SOLECTRUS, Version 0.16.0, built at 2024-08-30T10:30:45.681Z
senec-collector-1  | https://github.com/solectrus/senec-collector
senec-collector-1  | Copyright (c) 2020-2024 Georg Ledermann, released under the MIT License
senec-collector-1  | 
senec-collector-1  | Using Ruby 3.3.4 on platform aarch64-linux-musl
senec-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement SENEC
senec-collector-1  | 
senec-collector-1  | Pulling from your local SENEC at https://192.168.001.230 every 5 seconds
senec-collector-1  | Getting state names (language: de) from SENEC by parsing source code...
admin@raspberrypi:/home/pi/solectrus $ docker compose logs shelly-collector
no such service: shelly-collector
```

**Reply by hambue** [reply]
Für die Logs der beiden Shelly-Collectoren musst du die exakten Namen der Services nennen. Gemäß dem obigen Beispiel sind diese `shelly-collector-aufzug` und `shelly-collector-therme`.

**Reply by Zeppelin-PV** [reply]
DANKE, für den Tipp, ... macht ja auch Sinn, 
hier nun die Logs vom Aufzug und von der Therme

```
shelly-collector-aufzug-1  | https://github.com/solectrus/shelly-collector
shelly-collector-aufzug-1  | Copyright (c) 2024 Georg Ledermann, released under the MIT License
shelly-collector-aufzug-1  | 
shelly-collector-aufzug-1  | bundler: failed to load command: app.rb (app.rb)
shelly-collector-aufzug-1  | /shelly-collector/lib/config.rb:129:in `fetch': key not found: "INFLUX_TOKEN" (KeyError)
shelly-collector-aufzug-1  | Did you mean?  "INFLUX_ORG"
shelly-collector-aufzug-1  | 	from /shelly-collector/lib/config.rb:129:in `from_env'
shelly-collector-aufzug-1  | 	from app.rb:24:in `<top (required)>'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/bin/bundle:25:in `load'
shelly-collector-aufzug-1  | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
```

```
shelly-collector-therme-1  | https://github.com/solectrus/shelly-collector
shelly-collector-therme-1  | Copyright (c) 2024 Georg Ledermann, released under the MIT License
shelly-collector-therme-1  | 
shelly-collector-therme-1  | bundler: failed to load command: app.rb (app.rb)
shelly-collector-therme-1  | /shelly-collector/lib/config.rb:129:in `fetch': key not found: "INFLUX_TOKEN" (KeyError)
shelly-collector-therme-1  | Did you mean?  "INFLUX_ORG"
shelly-collector-therme-1  | 	from /shelly-collector/lib/config.rb:129:in `from_env'
shelly-collector-therme-1  | 	from app.rb:24:in `<top (required)>'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
shelly-collector-therme-1  | 	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
shelly-collector-therme-1  | 	from /usr/local/bundle/bin/bundle:25:in `load'
shelly-collector-therme-1  | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
```

**Reply by ledermann** [reply]
Ok, mein Fehler, es muss in der `compose.yml` in beiden Fällen so heißen:

```
- INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
```

Und ich sehe noch einen Fehler, da fehlt ein $-Zeichen. Hier noch mal komplett:

```
shelly-collector-aufzug:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT=${SHELLY_MEASUREMENT_AUFZUG}
    - SHELLY_HOST=${SHELLY_HOST_AUFZUG}
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped

shelly-collector-therme:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT=${SHELLY_MEASUREMENT_THERME}
    - SHELLY_HOST=${SHELLY_HOST_THERME}
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
```

Wenn es dann immer noch nicht klappen sollte, dann bitte mal die `.env` zeigen.

**Reply by Zeppelin-PV** [reply]
in der Aufzug Log steht da was mit Therme - ?
nach Record 1 läuft es, so wie es aussieht

```
admin@raspberrypi:/home/pi/solectrus $ docker compose logs shelly-collector-aufzug
WARN[0000] The "SHELLY_MEASUREMENT_Therme" variable is not set. Defaulting to a blank string. 
shelly-collector-aufzug-1  | Shelly collector for SOLECTRUS, Version 0.3.4, built at 2024-08-30T10:33:58.404Z
shelly-collector-aufzug-1  | https://github.com/solectrus/shelly-collector
shelly-collector-aufzug-1  | Copyright (c) 2024 Georg Ledermann, released under the MIT License
shelly-collector-aufzug-1  | 
shelly-collector-aufzug-1  | Using Ruby 3.3.4 on platform aarch64-linux-musl
shelly-collector-aufzug-1  | Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement Aufzug
shelly-collector-aufzug-1  | Pulling from your Shelly at http://192.168.1.243 every 5 seconds
shelly-collector-aufzug-1  | 
shelly-collector-aufzug-1  | Got record #1 at 2024-09-02 22:33:46 +0200 within 74 ms, Power 46.4 W, Temperature 42.8 °C
shelly-collector-aufzug-1  | Error while pushing record #1 to InfluxDB: Failed to open TCP connection to influxdb:8086 (Connection refused - connect(2) for "influxdb" port 8086)
shelly-collector-aufzug-1  | The record has been queued. Will retry to push 1 records later.
shelly-collector-aufzug-1  | Successfully pushed record #1 to InfluxDB
shelly-collector-aufzug-1  | 
shelly-collector-aufzug-1  | Got record #2 at 2024-09-02 22:33:51 +0200 within 39 ms, Power 44.7 W, Temperature 42.7 °C
shelly-collector-aufzug-1  | Successfully pushed record #2 to InfluxDB
shelly-collector-aufzug-1  | 
shelly-collector-aufzug-1  | Got record #3 at 2024-09-02 22:33:56 +0200 within 32 ms, Power 42.6 W, Temperature 42.6 °C
shelly-collector-aufzug-1  | Successfully pushed record #3 to InfluxDB
shelly-collector-aufzug-1  | 
shelly-collector-aufzug-1  | Got record #4 at 2024-09-02 22:34:01 +0200 within 33 ms, Power 40.4 W, Temperature 42.8 °C
shelly-collector-aufzug-1  | Successfully pushed record #4 to InfluxDB
shelly-collector-aufzug-1  | 
shelly-collector-aufzug-1  | Got record #5 at 2024-09-02 22:34:07 +0200 within 45 ms, Power 41.0 W, Temperature 42.8 °C
shelly-collector-aufzug-1  | Successfully pushed record #5 to InfluxDB
```

hier die Therme Log

```
admin@raspberrypi:/home/pi/solectrus $ docker compose logs shelly-collector-therme
WARN[0000] The "SHELLY_MEASUREMENT_Therme" variable is not set. Defaulting to a blank string. 
shelly-collector-therme-1  | Shelly collector for SOLECTRUS, Version 0.3.4, built at 2024-08-30T10:33:58.404Z
shelly-collector-therme-1  | https://github.com/solectrus/shelly-collector
shelly-collector-therme-1  | Copyright (c) 2024 Georg Ledermann, released under the MIT License
shelly-collector-therme-1  | 
shelly-collector-therme-1  | Using Ruby 3.3.4 on platform aarch64-linux-musl
shelly-collector-therme-1  | Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement Consumer
shelly-collector-therme-1  | Pulling from your Shelly at http://192.168.1.244 every 5 seconds
shelly-collector-therme-1  | 
shelly-collector-therme-1  | Got record #1 at 2024-09-02 22:33:46 +0200 within 107 ms, Power 6.1 W, Temperature 40.3 °C
shelly-collector-therme-1  | Error while pushing record #1 to InfluxDB: Failed to open TCP connection to influxdb:8086 (Connection refused - connect(2) for "influxdb" port 8086)
shelly-collector-therme-1  | The record has been queued. Will retry to push 1 records later.
shelly-collector-therme-1  | Successfully pushed record #1 to InfluxDB
shelly-collector-therme-1  | 
shelly-collector-therme-1  | Got record #2 at 2024-09-02 22:33:52 +0200 within 48 ms, Power 6.1 W, Temperature 40.4 °C
shelly-collector-therme-1  | Successfully pushed record #2 to InfluxDB
shelly-collector-therme-1  | 
shelly-collector-therme-1  | Got record #3 at 2024-09-02 22:33:57 +0200 within 37 ms, Power 6.1 W, Temperature 40.5 °C
shelly-collector-therme-1  | Successfully pushed record #3 to InfluxDB
shelly-collector-therme-1  | 
shelly-collector-therme-1  | Got record #4 at 2024-09-02 22:34:02 +0200 within 37 ms, Power 6.0 W, Temperature 40.3 °C
shelly-collector-therme-1  | Successfully pushed record #4 to InfluxDB
shelly-collector-therme-1  | 
shelly-collector-therme-1  | Got record #5 at 2024-09-02 22:34:07 +0200 within 36 ms, Power 6.1 W, Temperature 40.4 °C
shelly-collector-therme-1  | Successfully pushed record #5 to InfluxDB
```

und hier die .env

```env
##################################################################
###                          Generic                           ###
##################################################################

TZ=Europe/Berlin

##################################################################
###                   Dashboard application                    ###
##################################################################

# Domain name or IP address of your host
APP_HOST=my-little-raspbery.local

# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2022-09-01

# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=xxx

# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false

# Secret token to secure cookies, 128 chars long hexadecimal encoded string
SECRET_KEY_BASE=xxx

# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0

# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com

# Password for the PostgreSQL database, used by the app to communicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to connect to the database!
POSTGRES_PASSWORD=xxx

##################################################################
###                      Sensor mapping                        ###
##################################################################

# Where to find the data in the InfluxDB
# Each sensor must be mapped to a measurement and a field
# The format is: INFLUX_SENSOR_NAME=MEASUREMENT:FIELD
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power

INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
INFLUX_SENSOR_WALLBOX_POWER=
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_INVERTER_POWER_FORECAST=Forecast:watt
INFLUX_SENSOR_HEATPUMP_POWER=

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
# INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER,WALLBOX_POWER

##################################################################
###                      SENEC Collector                       ###
##################################################################

# The adapter to use
# Values: local, cloud
SENEC_ADAPTER=local

# The IP address or hostname of your SENEC device
# Available only when using the local adapter
SENEC_HOST=192.168.001.230

# The schema protocol to use
# Available only when using the local adapter
# Values: http, https
SENEC_SCHEMA=https

# The language to use for status strings
# Available only when using the local adapter
# Values: de, en, it
SENEC_LANGUAGE=de

# The credentials for mein-senec.de
# Available only when using the cloud adapter
# SENEC_USERNAME=me@example.com
# SENEC_PASSWORD=my-senec-password

# The system ID of your SENEC device
# Available only when using the cloud adapter
# Can be empty if there is just one system
# SENEC_SYSTEM_ID=123456

# The interval in seconds for polling
# Minimum for local adapter is 5 seconds
# Minimum for cloud adapter is 30 seconds
SENEC_INTERVAL=5

# Measurement name for InfluxDB
SENEC_INFLUX_MEASUREMENT=SENEC

# Optional: Disable specific fields you do not want to send to InfluxDB.
# This can be useful if you are tracking them from another source.
# Comma separated list of fields, no whitespace. Example:
# SENEC_IGNORE=wallbox_charge_power,grid_power_minus

##################################################################
###                     Forecast collector                     ###
##################################################################

FORECAST_PROVIDER=forecast.solar

# Number of planes (if you have more than one). Default is 1. Forecast.solar allows up to 4 planes, Solcast up to 2.
FORECAST_CONFIGURATIONS=3

# Update interval in seconds
FORECAST_INTERVAL=2700

# Measurement name for InfluxDB
FORECAST_INFLUX_MEASUREMENT=Forecast

### Details for forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate

# Latitude of the plant location
FORECAST_LATITUDE=xxx

# Longitude of the plant location
FORECAST_LONGITUDE=xxx

# Plane declination: 0 (horizontal) - 90 (vertical)
# FORECAST_DECLINATION=30

# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
# FORECAST_AZIMUTH=20

# Installed modules power in kilowatt peak (kWp)
# FORECAST_KWP=8.4

# Optional damping factors (http://doc.forecast.solar/damping)
# FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional configuration for multiple planes
#
# Starting from 0, add params different from the values defined above
FORECAST_0_DECLINATION=24
FORECAST_0_AZIMUTH=-93
FORECAST_0_KWP=8.910
#
FORECAST_1_DECLINATION=24
FORECAST_1_AZIMUTH=87
FORECAST_1_KWP=2.835
#
FORECAST_2_DECLINATION=30
FORECAST_2_AZIMUTH=0
FORECAST_2_KWP=0.820
#
# FORECAST_3_DECLINATION=50
# FORECAST_3_AZIMUTH=90
# FORECAST_3_KWP=2.58
#
# Available params are:
# - FORECAST_x_LATITUDE
# - FORECAST_x_LONGITUDE
# - FORECAST_x_DECLINATION
# - FORECAST_x_AZIMUTH
# - FORECAST_x_KWP
# - FORECAST_x_DAMPING_MORNING
# - FORECAST_x_DAMPING_EVENING

# Optional API key for registered users of forecast.solar (https://doc.forecast.solar/account_models)
# FORECAST_SOLAR_APIKEY=abc123

### Details for solcast.com

# SOLCAST_APIKEY=secret-solcast-api-key
# SOLCAST_SITE=1111-2222-3333-4444

# SOLCAST_0_SITE=1111-2222-3333-4444
# SOLCAST_1_SITE=5555-6666-7777-8888
#
#
#################################################################
###             Shelly Collector                              ###
#################################################################
#
SHELLY_INTERVAL=5
SHELLY_HOST_THERME=192.168.1.244
SHELLY_HOST_AUFZUG=192.168.1.243
SHELLY_MEASUREMENT_THERME=Therme
SHELLY_MEASUREMENT_AUFZUG=Aufzug
#
##################################################################
###                 InfluxDB time series database              ###
##################################################################

# InfluxDB host
INFLUX_HOST=influxdb

# InfluxDB schema (http or https)
INFLUX_SCHEMA=http

# InfluxDB port
INFLUX_PORT=8086

# Credentials for the InfluxDB, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=xxx
INFLUX_ADMIN_TOKEN=xxx

# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=my-solectrus-bucket

# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=xxx
INFLUX_TOKEN_READ=xxx

# Volume path for storing the InfluxDB data
INFLUX_VOLUME_PATH=/home/pi/solectrus/influxdb

##################################################################
###                    PostgreSQL database                     ###
##################################################################

# Volume path for storing the PostgreSQL data
DB_VOLUME_PATH=/home/pi/solectrus/postgresql

##################################################################
###                 Redis in-memory database                   ###
##################################################################

# Volume path for storing the database snapshot
REDIS_VOLUME_PATH=/home/pi/solectrus/redis
```

**Reply by Zeppelin-PV** [reply]
WARN[0000] The "SHELLY_MEASUREMENT_Therme"
-- Großschreibung nicht beachtet - THERME

**Reply by ledermann** [reply]
Ok, damit funktioniert es nun offenbar.

Du könntest noch folgende Zeilen in der Compose-Datei ergänzen, damit beim ersten Start keine Fehlermeldung auftritt, wenn InfluxDB noch nicht bereit ist und außerdem der Collector mit Watchtower aktuell gehalten wird (falls du Watchtower verwendest).

```yaml
depends_on:
  influxdb:
    condition: service_healthy
links:
  - influxdb
labels:
  - com.centurylinklabs.watchtower.scope=solectrus     
```

Insgesamt also so:

```yaml
shelly-collector-aufzug:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT=${SHELLY_MEASUREMENT_AUFZUG}
    - SHELLY_HOST=${SHELLY_HOST_AUFZUG}
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
  depends_on:
    influxdb:
      condition: service_healthy
  links:
    - influxdb
  labels:
    - com.centurylinklabs.watchtower.scope=solectrus

shelly-collector-therme:
  image: ghcr.io/solectrus/shelly-collector:latest
  environment:
    - TZ
    - INFLUX_SCHEMA
    - INFLUX_HOST
    - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
    - INFLUX_ORG
    - INFLUX_BUCKET
    - INFLUX_PORT
    - INFLUX_MEASUREMENT=${SHELLY_MEASUREMENT_THERME}
    - SHELLY_HOST=${SHELLY_HOST_THERME}
    - SHELLY_INTERVAL
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
  depends_on:
    influxdb:
      condition: service_healthy
  links:
    - influxdb
  labels:
    - com.centurylinklabs.watchtower.scope=solectrus
```

Ich denke, damit sind wir hier durch :)
