### DISCUSSION TITLE
Wallbox nachträglich eintragen

### DISCUSSION THREAD

**Discussion by Nemo3006** [solectrus/solectrus#3496] [Q&A] [answered]
Hallo zusammen, 
ich bin schon etwas länger dabei und habe Solectrus (in der Cloud) schon genutzt, als es den Konfigurator noch nicht gab. Nun bin ich als "Unterstützer" / "Sponsor" oder was auch immer ja in der Lage, auch eine Wallbox anzeigen zu lassen. Dazu musste man aber noch etwas in seiner Konfiguration ändern. Ich finde dazu leider nirgendwo eine Anleitung. Vermutlich bin ich blind und wäre daher froh wenn mich kurz jemand zur entsprechenden Doku leiten könnte...Viele Grüße

**Comment by ledermann** [comment]
Ob für die Darstellung der Wallbox etwas einzustellen ist, hat damit zu tun, wo denn bei dir die Messwerte herkommen. Hast du eine SENEC-Wallbox und verwendest den SENEC-Collector? Dann kommen Wallbox-Werte automatisch und werden auch angezeigt. Hast du eine andere Wallbox und die Messwerte kommen per MQTT? Dann muss der Sensor `INFLUX_SENSOR_WALLBOX_POWER` [konfiguriert](https://github.com/solectrus/solectrus/wiki/Konfiguration) werden.

Eine Wallbox wird übrigens schon immer unterstützt, das hat mit dem Sponsoring nichts zu tun. Meinst du vielleicht den Power-Splitter? Dazu gibt es hier eine Doku:
https://github.com/solectrus/power-splitter/wiki/Installation

Falls das alles nicht hilft: Was genau meinst du und welche Probleme stellen sich?

**Reply by Nemo3006** [reply]
Aaaalso. Nein ich habe keine senec wallbox sondern eine Zaptec. Irgendwo muss ich ja die Daten in meine bestehende Konfiguration eintragen. Sponsor bin ich geworden um dich zu unterstützen, aber die zusätzlichen Features nehme ich gerne mit.

**Reply by ledermann** [reply]
Ok, Unterstützung ist immer gut :-) 

Mir ist aber noch nicht klar, vor welchem Problem wir stehen:

- Wird die Wallbox nicht in SOLECTRUS angezeigt? Dann wäre der Sensor `INFLUX_SENSOR_WALLBOX_POWER` zu prüfen. 
- Oder möchtest du den PowerSplitter für die Wallbox aktivieren? Dafür findest du die Anleitung hier: https://github.com/solectrus/power-splitter/wiki/Installation

**Comment by Nemo3006** [comment]
Ich sehe die wallbox nicht. Wenn ich das richtig verstanden habe brauche ich dafür den entsprechenden sensor. In diesem Fall influx_sensor_wallbox_power. Den muss ich aber doch erst einmal in meine Installation rein wurschteln oder? Der wird ja zu Anfang noch nicht dabei gewesen sein. Der splitter ist sicher auch interessant, aber erst einmal eines nach dem anderen.

**Reply by ledermann** [reply]
OK, jetzt verstehe ich. Es ist Folgendes zu tun:

1. Dafür sorgen, dass der Wallbox-Messwert in deinem MQTT-Broker verfügbar ist. 

2. Sicherheitshalber alle Container auf den aktuellen Stand bringen: `docker compose pull && docker compose up -d`

3. Idealerweise auf die neue Sensor-Konfiguration umstellen: https://github.com/solectrus/solectrus/wiki/Umstellung-auf-neue-Sensor%E2%80%90Konfiguration

4. Den MQTT-Collector so einrichten, dass der Messwert beim MQTT-Broker abgeholt wird. Doku hier: https://github.com/solectrus/mqtt-collector/wiki/Konfiguration

5. Das Dashboard so konfigurieren, dass es den Sensor kennt:

   In der `.env` einen Eintrag wie etwa diesen hier ergänzen:      

   ```env
   INFLUX_SENSOR_WALLBOX_POWER=zaptec:wallbox_power
   ```

   In der `docker-compse.yml` unter `services/app/environment` diese Zeile ergänzen:

   ```yaml
   - INFLUX_SENSOR_WALLBOX_POWER
   ```

Falls es weiterhin Probleme gibt, poste mal deine `.env` und `docker-compose.yml`.

**Reply by Nemo3006** [reply]
Puuh...Das kriege ich bestimmt nicht hin. Das ganze Ding mit dem neuen Konfigurator neu aufzusetzen geht bestimmt schneller und einfacher oder?

**Reply by ledermann** [reply]
Ja, das ist einfacher - aber dann werden deine Messwerte an einem anderen Ort in InfluxDB gespeichert und gesucht, d.h. du verlierst dann die Historie.

Hast du denn Punkt 1 geklärt? Dann gib mir mal deine `.env` und `docker-compose.yml`, dann passe ich das für dich an.

**Reply by Nemo3006** [reply]
Ich hlhabe soweit ich weiß keinen MQTT Broker. Damit fängt es ja schon an. In der docker-compose jedenfalls steht davon nichts. Evtl bin ich jetzt aber auch komplett auf dem Holzweg.

**Reply by ledermann** [reply]
Ja, sieht sehr nach Holzweg aus ;-)

In den allermeisten (*, **) Fällen kommen Wallbox-Messwerte nur über MQTT zu SOLECTRUS. Das bedeutet: Du brauchst irgendwo einen MQTT-Broker. Und du brauchst ein Tool, das die Wallbox abfragen kann und dem MQTT-Broker schickt. Optionen sind ioBroker/HomeAssistant/Mosquitto. Falls du nichts davon hast, würde ich ioBroker empfehlen, da ist ein MQTT-Broker drin enthalten.

(*) Erste Ausnahme: SENEC-Wallbox am SENEC-Speicher. Dessen Messwerte können über den [SENEC-Collector](https://github.com/solectrus/senec-collector) abgefragt werden.

(**) Zweite Ausnahme: An der Wallbox hängt ein Shelly Pro 3EM. Dann könnte der [Shelly-Collector](https://github.com/solectrus/shelly-collector) hilfreich sein.

**Comment by Nemo3006** [comment]
Das klingt ja schon einmal gut. Iobroker habe ich. Ich habe auch EVCC falls das hilft. 🤷

**Reply by ledermann** [reply]
Ok, der Weg ist nun:

1) Im ioBroker den MQTT-Broker aktivieren
2) In evcc dafür sorgen, dass die Messwerte der Wallbox zum MQTT-Broker geschickt werden
3) In SOLECTRUS dann den MQTT-Collector einrichten, um die Wallbox-Messwerte beim MQTT-Broker abzuholen

Bei 3) kann ich dir helfen, aber 1) und 2) musst du selber hinbekommen.

**Comment by Nemo3006** [comment]
Aya aye, Captain! Ich melde mich, wenn ich soweit bin! Danke soweit!

**Comment by Nemo3006** [comment]
Schritte 1 und 2 erledigt 🙂

**Comment by ledermann** [comment]
Ok, dann wäre nun der MQTT-Collector dran:
https://github.com/solectrus/mqtt-collector/wiki/Konfiguration

**Comment by Nemo3006** [comment]
Danke. Das erklärt aber ja nur einige Dinge innerhalb des collectors. Diesen muss ich aber erst einmal installieren. Kann ich dafür diese Anleitung nehmen?   https://github.com/solectrus/hosting/tree/main/guide/mqtt-iobroker

**Reply by ledermann** [reply]
Ja, für das spätere Hinzufügen von Collectoren gibt es noch zu wenig Dokumentation. 

Anstelle der alten Anleitung würde ich dann eher den Konfigurator nehmen, und nur die Zeilen aus `docker-compose.yml` und `.env` nehmen, die für den MQTT-Collector relevant sind.

Wenn du das alles nicht hinbekommst: Poste deine jetzige `.env` und `docker-compose.yml`, dann ergänze ich das.

**Comment by Nemo3006** [comment]
Jetzt bekomme ich einen Error500...ich wusste doch dass ich es besser gelassen hätte :-( Folgendes steht in der .env:

```
root@docker-ce-ubuntu-4gb-nbg1-1:~/solectrus# nano .env

  GNU nano 6.2                                     .env                                              
##################################################################
# Dashboard application (the main part)
#
# Domain name or IP address of your host
APP_HOST=my-little-raspberry.local
#
# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid S>
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false
#
# Secret token to secure cookies, 128 chars long hexadecimal encoded string (don't use this example,>
# Currently there are no cookies in Soletrus, but this may change in the future
SECRET_KEY_BASE=XXXXXX>
#
# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2022-01-27
#
# Password for the PostgreSQL database, used by the app to comunicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to conne>
POSTGRES_PASSWORD=XXX
#
# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=XXX
#
# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com
#
# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0
#

##################################################################
# Influx database settings
#
# Influx host (to access from SOLECTRUS dashboard and collectors)
INFLUX_HOST=influxdb
INFLUX_SCHEMA=http
INFLUX_PORT=8086
#
# Credentials for the Influx database, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=XXX
INFLUX_ADMIN_TOKEN=XXX
#
# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=solectrus
INFLUX_MEASUREMENT_PV=my-pv-measurement
INFLUX_MEASUREMENT_FORECAST=Forecast
#
# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=XXX
INFLUX_TOKEN_READ=XXX
#
# Volume path for storing the Influx data
INFLUX_VOLUME_PATH=./influxdb
#
# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

##################################################################
# REDIS settings
#
REDIS_VOLUME_PATH=./redis

##################################################################
# PostgreSQL database settings
#
DB_VOLUME_PATH=./postgresql

##################################################################
# MQTT Collector

# MQTT Broker credentials
MQTT_HOST=192.168.178.116
MQTT_PORT=1883
MQTT_SSL=false
MQTT_USERNAME=
MQTT_PASSWORD=

# MQTT topics (this is only an example, change to your needs!)
# This example is for using https://github.com/nobl/ioBroker.senec (which in most cases is not neces>
MQTT_EVCC_HOUSE_POW=senec/0/ENERGY/GUI_HOUSE_POW
MQTT_EVCC_GRID_POW=senec/0/ENERGY/GUI_GRID_POW
MQTT_EVCC_BAT_CHARGE_CURRENT=senec/0/ENERGY/GUI_BAT_DATA_CURRENT
MQTT_EVCC_BAT_FUEL_CHARGE=senec/0/ENERGY/GUI_BAT_DATA_FUEL_CHARGE
MQTT_EVCC_BAT_POWER=senec/0/ENERGY/GUI_BAT_DATA_POWER
MQTT_EVCC_BAT_VOLTAGE=senec/0/ENERGY/GUI_BAT_DATA_VOLTAGE
MQTT_EVCC_CASE_TEMP=senec/0/TEMPMEASURE/CASE_TEMP
# MQTT options
MQTT_FLIP_BAT_POWER=false

##################################################################
# Solar forecasting with https://forecast.solar or https:://solcast.com
#
# Forecast.solar docs: https://doc.forecast.solar/doku.php?id=api:estimate
# Solcast docs: https://docs.solcast.com.au/
#
# Choose between "forecast.solar" and "solcast", default is "forecast.solar"
FORECAST_PROVIDER=forecast.solar

##### For provider "solcast" only:
#
# First, sign up for a free account at https://toolkit.solcast.com.au/ and
# create a "site" for your PV system.
# Up to two strings are supported, both will be assigned an ID that looks like "1234-5678-9abc-def0"
#
# API key for Solcast
# SOLCAST_APIKEY=secret-solcast-api-key
#
# For single string:
# SOLCAST_SITE=1111-2222-3333-4444
#
# For multiple strings (see See https://kb.solcast.com.au/creating-a-second-pv-site)
# FORECAST_CONFIGURATIONS=2
# SOLCAST_0_SITE=1111-2222-3333-4444
# SOLCAST_1_SITE=5555-6666-7777-8888
#
# Update interval in seconds (beware of the rate-limit!, 10 requests per day only!)
# FORECAST_INTERVAL=8640
#
##### For provider "forecast.solar" only:
#
# Latitude of the plant location
FORECAST_LATITUDE=50.12345
#
# Longitude of the plant location
FORECAST_LONGITUDE=6.12345
#
# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_DECLINATION=30
#
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
FORECAST_AZIMUTH=20
#
# Installed modules power in kilowatt peak (kWp)
FORECAST_KWP=8.4
#
# Optional damping factors (http://doc.forecast.solar/damping)
 FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional horizon (https://doc.forecast.solar/api#horizon)
# FORECAST_HORIZON=0,0,0,0,0,0,10,20,20,20,20,20
#
# Optional inverter limit (https://doc.forecast.solar/api#inverter)
# FORECAST_INVERTER=3.5
#
# Optional configuration for multiple planes
#
# Number of planes
# FORECAST_CONFIGURATIONS=2
#
# Starting from 0, add params different from the values defined above
# FORECAST_0_AZIMUTH=90
# FORECAST_0_KWP=5.32
# FORECAST_1_AZIMUTH=-90
# FORECAST_1_KWP=7.84
#
# Available params are:
# - FORECAST_x_LATITUDE
# - FORECAST_x_LONGITUDE
# - FORECAST_x_DECLINATION
# - FORECAST_x_AZIMUTH
# - FORECAST_x_KWP
# - FORECAST_x_DAMPING_MORNING
# - FORECAST_x_DAMPING_EVENING
#
# Update interval in seconds, 900s = 15 minutes, the public (and free) API allows a minimum of 900 s>
# BEWARE: Each plane counts as one request, so if you have multiple planes, you need to multiply the>
FORECAST_INTERVAL=900
#
# Optional API key for registered users of forecast.solar (https://doc.forecast.solar/account_models)
# FORECAST_SOLAR_APIKEY=abc123`
```

Die docker-compose.yml kommt gleich ...

**Comment by Nemo3006** [comment]
```
GNU nano 6.2                                                                                  docker-compose.yml                                                                                            
version: '3.7'

services:
  app:
    image: ghcr.io/solectrus/solectrus:latest
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      db:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - db
      - influxdb
      - redis
    ports:
      - 80:3000
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - DB_HOST=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT_PV
      - INFLUX_MEASUREMENT_FORECAST
      - INFLUX_POLL_INTERVAL
      - WEB_CONCURRENCY
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 3000 || exit 1']
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  influxdb:
    image: influxdb:2.7-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2

^G Help          ^O Write Out     ^W Where Is      ^K Cut           ^T Execute       ^C Location      M-U Undo         M-A Set Mark     M-] To Bracket   M-Q Previous     ^B Back          ^◂ Prev Word
^X Exit          ^R Read File     ^\ Replace       ^U Paste         ^J Justify       ^/ Go To Line    M-E Redo         M-6 Copy         ^Q Where Was     M-W Next         ^F Forward       ^▸ Next Word
```
