### DISCUSSION TITLE
solectrus-db-1 is unhealthy

### DISCUSSION THREAD

**Discussion by KippA67** [solectrus/solectrus#3748] [Q&A] [answered]
Hallo zusammen,
seit gestern bekomme ich im Browser keine Verbindung mehr zu Solectrus (läüft auf einem Raspberry)..
Wenn ich versuche, ein Update zu laden dann funktioniert das, bei Installierern dieses Updates bekomme ich allerdings die Meldung "dependency failed to start: container solectrus-db-1 is unhealthy"...

Irgendjemand eine Idee wie ich das wieder zum laufen bekomme?

**Comment by gereons** [comment]
Irgendwas ist mit deiner PostgrSQL-Datenbank nicht in Ordnung. Poste doch bitte mal die Ausgabe von `docker logs solectrus-db-1`, da steht hoffentlich was aussagekräftiges drin.

**Comment by ledermann** [comment]
Meine Vermutung wäre: Du hast versehentlich ein Major-Upgrade von PostgreSQL versucht, also z.B. von `16-alpine` auf `17-alpine` gewechselt. Ein Major-Upgrade ist bei PostgreSQL aber nicht so einfach, eine bestehende Datenbank muss dafür migriert werden. Die Lösung wäre hier: Wieder zurück auf die vorher benutzte Version.

Wenn das nicht die Ursache ist: Wie @gereons bereits geschrieben hat - im Log wird höchstwahrscheinlich die Ursache stehen.

**Comment by gereons** [comment]
> Du hast versehentlich ein Major-Upgrade von PostgreSQL versucht, also z.B. von 16-alpine auf 17-alpine gewechselt.   

Frage in dem Zusammenhang: taugt der psql-Teil der Backup/Restore-Scripte um so einen Upgrade zu machen?

**Reply by ledermann** [reply]
Ja, habe in https://github.com/solectrus/backup-restore/issues/5 etwas dazu geschrieben.

**Comment by KippA67** [comment]
Danke für die schnellen Antworten, die Lösung schint woh einfacher zu sein, das Logfile hat geholfen::

pi@raspberrypi:~ $ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root       15020736 14541284         0 100% /
devtmpfs          781084        0    781084   0% /dev
tmpfs             946812        0    946812   0% /dev/shm
tmpfs             378728     1428    377300   1% /run
tmpfs               5120        4      5116   1% /run/lock
/dev/mmcblk0p1    261108    31298    229810  12% /boot
tmpfs             189360        0    189360   0% /run/user/1000 

SD-Karte ist wohl voll 😒😏

Ich werde mal versuchen die auf eine größere zu klonen...

**Reply by ledermann** [reply]
Bevor du auf eine größere Karte wechselst: Was verbraucht denn da so viel Platz? Wird der Verbrauch von SOLECTRUS verursacht oder von anderen Dingen?

```
docker system df -v
```

Laufen die Logs voll? In `compose.yaml` sollte bei jedem Service das hier (oder ähnlich) stehen:

```yaml
logging:
   options:
     max-size: 10m
     max-file: '3'
```

**Comment by KippA67** [comment]
Hmm,
hier mal die Ausgabe von "docker system df -v" & die docker-compse.yml (eine compse.yaml hab ich nicht gefunden...)

[docker_system_df .txt](https://github.com/user-attachments/files/18047826/docker_system_df.txt)
[docker-compose.yml.txt](https://github.com/user-attachments/files/18047828/docker-compose.yml.txt)

Ist jetzt aber auch nicht "eilig", ich bin gleich eh unterwegs und würde mich erst morgen wieder an den Rechner setzten, Weihnachtsmarkt & Co rufen 😏😏😏

**Reply by gereons** [reply]
Da liegen noch jede Menge alte Container und Images rum die du bedenkenlos löschen kannst. `docker image prune -a` und `docker container prune` sollten einiges an Platz freischaufeln, und die logging-Optionen solltest du auch nachtragen.

**Reply by ledermann** [reply, marked as answer]
Ja, sehe ich auch so, die alten Container und Images können weg.

Da die Installation bereits seit zwei Jahren läuft und keine Logging-Limitierung aktiv ist, vermute ich eine riesige Menge an Logfiles, zu ermitteln z.B. so:

```
sudo find /var/lib/docker/containers -name "*.log" -exec du -sh {} +
```

Ein Leeren wäre folgendermaßen möglich:

```
sudo find /var/lib/docker/containers -name "*.log" -exec truncate -s 0 {} +
```

Anschließend die obigen Logging-Optionen in deiner `docker-compose.yml` ergänzen (bei **allen** Services), damit das Problem nicht irgendwann erneut auftritt, also so:

```
logging:
  options:
    max-size: 10m
    max-file: "3"
```

Noch der Änderung des Compose-Files `docker compose up -d` ausführen, damit es aktiv wird.

Und zack, neue SD-Karte gespart ;-)

**Comment by KippA67** [comment]
Wow, der Service ist hier ja mega 👍
Es läuft wieder, nur bin ich mir nicht sicher, wo genau ich in der docker-compose.yml die Einträge bzgl. des Loggings eintragen muß...
Was sind denn die "Services", sind das z.B. "influx-db", "db", "redis", "senec-collector" usw.?

Nochmal Danke für die schnelle Hilfe (und das auch noch auf Deutsch 😏) -> Sponsoring ist aktiviert 🫡😉

**Reply by ledermann** [reply]
Prima, freut mich, dass es geholfen hat - und danke für das Sponsoring :)

Die Einträge sollten so aussehen, bei jedem einzelnen Service (dashboard, influxdb, ...):

```yaml
services:
  app:
    ...
    logging:
      options:
        max-size: 10m
        max-file: '3'
  influxdb:
    ...
    logging:
      options:
        max-size: 10m
        max-file: '3'
  db:
    ...
    logging:
      options:
        max-size: 10m
        max-file: '3'
  redis:
    ...
    logging:
      options:
        max-size: 10m
        max-file: '3'
  senec-collector:
    ...
    logging:
      options:
        max-size: 10m
        max-file: '3'
  forecast-collector:
    ...
    logging:
      options:
        max-size: 10m
        max-file: '3'
```

Wichtig: Unbedingt auf die richtige Einrückung achten!
