### DISCUSSION TITLE
Shelly Collector extrahieren einer Phase für custom consumer

### DISCUSSION THREAD

**Discussion by Zeppelin-PV** [solectrus/solectrus#3983] [Q&A] [answered]
hallo Georg
ich habe schon lange Zeit ein Shelly pro 3em in Solectrus mitlaufen - mehr oder weniger unbenutzt.
im DataExplorer der Influx schön zu sehen
![grafik](https://github.com/user-attachments/assets/1764edd6-7788-460a-950d-7794965117f0)

Nun möchte ich für die custom consumer power_a des Shelly nutzen (später, wenn das BKW verwirklicht wird power_c)
Ich muss den nächsten INFLUX_SENSOR_CUSTOM_POWER_XX in der .env belegen, soweit klar

Ist hier im Shelly Collector etwas zu ändern ? (es geht hier um den Shelly Terrasse)

```env
SHELLY_INTERVAL=5
SHELLY_HOST_TERRASSE=192.168.1.241
SHELLY_HOST_AUFZUG=192.168.1.243
SHELLY_HOST_THERME=192.168.1.244
SHELLY_MEASUREMENT_TERRASSE=TERRASSE
SHELLY_MEASUREMENT_AUFZUG=AUFZUG
SHELLY_MEASUREMENT_THERME=THERME
```

hier in der docker-compose ???

```yaml
  shelly-collector-terrasse:
    image: ghcr.io/solectrus/shelly-collector:develop
    environment:
      - TZ
      - INFLUX_SCHEMA
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_PORT
      - INFLUX_MEASUREMENT=${SHELLY_MEASUREMENT_TERRASSE}
      - SHELLY_HOST=${SHELLY_HOST_TERRASSE}
      - SHELLY_INTERVAL
      ....
```

denke Du kannst mir da sicher weiterhelfen
LG Ernst

gerade fällt mir ein, ich könnte ja den power_a Verbraucher ses Shelly über HomeAssistant holen
hier weiß ich ja nun wie es geht
was ist besser ?
was ist schöner ?
![grafik](https://github.com/user-attachments/assets/51787867-1e6f-41e1-91a4-c4b999ef2505)
