### DISCUSSION TITLE
Anleitung Power-spliter

### DISCUSSION THREAD

**Discussion by norbertle** [solectrus/solectrus#4004] [General]
Gibt es eine einfach Anleitung wie man den Power Splitter mit Änderungen der .env und docker-compose.yml aktivieren kann?
Sprich was wo eingefügt werden muss?

**Comment by ledermann** [comment]
Erste Anlaufstelle ist das hier:
https://docs.solectrus.de/referenz/power-splitter/

Aktuell gibt es einen Betatest für selbstdefinierte Verbraucher, der auch Auswirkungen aus den PowerSplitter an. Hier gibt es mehr Infos dazu:
https://github.com/orgs/solectrus/discussions/3749

**Comment by norbertle** [comment]
doccker-compse up -d 
liefert
services.power-splitter.logging.options must be a mapping
Wo muss man da dann noch was ändern?

**Reply by ledermann** [reply]
Da hast du irgendeinen Tippfehler in deiner `compose.yaml`. Ohne Kenntnis deiner `compose.yaml` kann ich leider nichts Genaueres sagen.

**Reply by norbertle** [reply]
Ich habe nur die Section des Service zu den anderen Services hinzugefügt per Copy und Paste.
Die Werte der vorhanden Services habe ich mal ausgelöscht hier. 

```yaml
version: '3.7'

services:
  app:
   

  influxdb:
   

  db:
   

  redis:
   

  senec-collector:
   

  forecast-collector:
   

  watchtower:
    image: containrrr/watchtower
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope solectrus --cleanup
 # ...
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:latest
    environment:
      - TZ
      - POWER_SPLITTER_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL
    logging:
      options:
      max-size: 10m
      max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - influxdb
      - redis
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```

**Reply by ledermann** [reply]
Der Fehler liegt in der fehlenden Einrückung. Die betreffenden Zeilen müssen so aussehen:

```yaml
logging:
  options:
    max-size: 10m
    max-file: '3'
```
