### DISCUSSION TITLE
Historische Daten nach Umzug

### DISCUSSION THREAD

**Discussion by loebse** [solectrus/solectrus#4246] [Q&A]
### Beschreibung (auf Deutsch oder Englisch)

Hallo Georg,

ich habe mich seit sehr langer Zeit (wann kam nochmal die Idee mit dem MQTT Collector auf?) wieder mit dem Fortschritt von Solectrus beschäftigt. Ich habe heute ein Update von einer sehr alten Version (kann leider nicht mehr nachvollziehen welche genau, aber sicher > 1 Jahr) gemacht. 

Soweit scheint auch alles zu laufen, ich hatte folgende Herausforderungen:

- Verwendung von Prostgres 15 statt 17
- Historische Daten waren zunächst nicht zu sehen, offensichtlich hat sich das InfluxDB Schema verändert:

![Image](https://github.com/user-attachments/assets/ba3b792f-b294-41d3-a613-3226f41d6941)

Nach Umstellung des Mappings von ``pv``auf ``pv-data``sehe ich zumindest wieder einige historische Daten.

Was mir jetzt noch fehlt ist folgendes:
Ich bekomme einige historische Daten, wie z.B. in "OVERALL"

![Image](https://github.com/user-attachments/assets/a2cc35cb-ccdd-4a50-9b78-4ca28c2241e0)

Allerdings scheint nicht alles da zu sein, wie z.B. in "WEEK"

![Image](https://github.com/user-attachments/assets/cade2cb7-41ee-4725-a6ce-7e8e294068b9)

Hast Du einen Tipp für mich, wo ich schauen soll?

### Welche Version von SOLECTRUS verwendest du?

v0.19.1

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Homeserver, Proxmox, LXC

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text

```

### Dein vollständiges `docker-compose.yml` oder `compose.yml`

```yaml
services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:latest
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3003:3000
    environment:
      - TZ
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - UI_THEME
      - CO2_EMISSION_FACTOR
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_CAR_BATTERY_SOC
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - TZ
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  postgresql:
    image: postgres:15-alpine
    environment:
      - TZ
      - POSTGRES_PASSWORD
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  redis:
    image: redis:7-alpine
    environment:
      - TZ
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest
    environment:
      - TZ
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - MAPPING_0_TOPIC
      - MAPPING_0_MEASUREMENT
      - MAPPING_0_FIELD
      - MAPPING_0_TYPE
      - MAPPING_1_TOPIC
      - MAPPING_1_MEASUREMENT
      - MAPPING_1_FIELD
      - MAPPING_1_TYPE
      - MAPPING_2_TOPIC
      - MAPPING_2_MEASUREMENT_POSITIVE
      - MAPPING_2_MEASUREMENT_NEGATIVE
      - MAPPING_2_FIELD_POSITIVE
      - MAPPING_2_FIELD_NEGATIVE
      - MAPPING_2_TYPE
      - MAPPING_3_TOPIC
      - MAPPING_3_MEASUREMENT_POSITIVE
      - MAPPING_3_MEASUREMENT_NEGATIVE
      - MAPPING_3_FIELD_POSITIVE
      - MAPPING_3_FIELD_NEGATIVE
      - MAPPING_3_TYPE
      - MAPPING_4_TOPIC
      - MAPPING_4_MEASUREMENT
      - MAPPING_4_FIELD
      - MAPPING_4_TYPE
      - MAPPING_5_TOPIC
      - MAPPING_5_MEASUREMENT
      - MAPPING_5_FIELD
      - MAPPING_5_TYPE
      - MAPPING_6_TOPIC
      - MAPPING_6_MEASUREMENT
      - MAPPING_6_FIELD
      - MAPPING_6_TYPE
      - MAPPING_7_TOPIC
      - MAPPING_7_MEASUREMENT
      - MAPPING_7_FIELD
      - MAPPING_7_TYPE
      - MAPPING_8_TOPIC
      - MAPPING_8_MEASUREMENT
      - MAPPING_8_FIELD
      - MAPPING_8_TYPE
      - MAPPING_9_TOPIC
      - MAPPING_9_MEASUREMENT
      - MAPPING_9_FIELD
      - MAPPING_9_TYPE
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    environment:
      - TZ
      - FORECAST_PROVIDER
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_CONFIGURATIONS
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_3_DECLINATION
      - FORECAST_3_AZIMUTH
      - FORECAST_3_KWP
      - FORECAST_INTERVAL
      - FORECAST_SOLAR_APIKEY
      - FORECAST_DAMPING_MORNING
      - FORECAST_DAMPING_EVENING
      - FORECAST_HORIZON
      - FORECAST_INVERTER
      - SOLCAST_APIKEY
      - SOLCAST_SITE
      - SOLCAST_0_SITE
      - SOLCAST_1_SITE
      - INFLUX_HOST
      - INFLUX_PORT
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_FORECAST}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:latest
    environment:
      - TZ
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL
      - POWER_SPLITTER_INTERVAL
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
```

### Dein vollständiges `.env`

```text
TZ=Europe/Berlin
APP_HOST=...
INSTALLATION_DATE=2021-09-02
ADMIN_PASSWORD=...
INFLUX_POLL_INTERVAL=5
FORCE_SSL=false
SECRET_KEY_BASE=...
WEB_CONCURRENCY=0
POSTGRES_PASSWORD=...
INFLUX_SENSOR_INVERTER_POWER=pv-data:inverter_power
INFLUX_SENSOR_HOUSE_POWER=pv-data:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=pv-data:grid_import_power
INFLUX_SENSOR_GRID_EXPORT_POWER=pv-data:grid_export_power
INFLUX_SENSOR_BATTERY_CHARGING_POWER=pv-data:battery_charging_power
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=pv-data:battery_discharging_power
INFLUX_SENSOR_BATTERY_SOC=pv-data:battery_soc
INFLUX_SENSOR_WALLBOX_POWER=pv-data:wallbox_power
INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=pv-data:car_connected
INFLUX_SENSOR_CASE_TEMP=pv-data:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=pv-data:system_status
INFLUX_SENSOR_SYSTEM_STATUS_OK=
INFLUX_SENSOR_GRID_EXPORT_LIMIT=
INFLUX_SENSOR_INVERTER_POWER_FORECAST=forecast:watt
INFLUX_SENSOR_HEATPUMP_POWER=
INFLUX_SENSOR_CAR_BATTERY_SOC=car:battery_soc
MQTT_HOST=...
MQTT_PORT=1883
MQTT_SSL=false
MQTT_USERNAME=...
MQTT_PASSWORD=...
MAPPING_0_TOPIC=solectrus/solar_power
MAPPING_0_MEASUREMENT=pv
MAPPING_0_FIELD=inverter_power
MAPPING_0_TYPE=integer
MAPPING_1_TOPIC=solectrus/house_consumption
MAPPING_1_MEASUREMENT=pv
MAPPING_1_FIELD=house_power
MAPPING_1_TYPE=integer
MAPPING_2_TOPIC=solectrus/grid_power
MAPPING_2_MEASUREMENT_POSITIVE=pv
MAPPING_2_MEASUREMENT_NEGATIVE=pv
MAPPING_2_FIELD_POSITIVE=grid_import_power
MAPPING_2_FIELD_NEGATIVE=grid_export_power
MAPPING_2_TYPE=integer
MAPPING_3_TOPIC=solectrus/bat_power
MAPPING_3_MEASUREMENT_POSITIVE=pv
MAPPING_3_MEASUREMENT_NEGATIVE=pv
MAPPING_3_FIELD_POSITIVE=battery_charging_power
MAPPING_3_FIELD_NEGATIVE=battery_discharging_power
MAPPING_3_TYPE=integer
MAPPING_4_TOPIC=solectrus/bat_percent
MAPPING_4_MEASUREMENT=pv
MAPPING_4_FIELD=battery_soc
MAPPING_4_TYPE=float
MAPPING_5_TOPIC=solectrus/wallbox_power
MAPPING_5_MEASUREMENT=pv
MAPPING_5_FIELD=wallbox_power
MAPPING_5_TYPE=integer
MAPPING_6_TOPIC=evcc/loadpoints/1/connected
MAPPING_6_MEASUREMENT=pv
MAPPING_6_FIELD=car_connected
MAPPING_6_TYPE=string
MAPPING_7_TOPIC=solectrus/case_temp
MAPPING_7_MEASUREMENT=pv
MAPPING_7_FIELD=case_temp
MAPPING_7_TYPE=float
MAPPING_8_TOPIC=solectrus/senec_status
MAPPING_8_MEASUREMENT=pv
MAPPING_8_FIELD=system_status
MAPPING_8_TYPE=string
MAPPING_9_TOPIC=evcc/loadpoints/1/vehicleSoc
MAPPING_9_MEASUREMENT=car
MAPPING_9_FIELD=battery_soc
MAPPING_9_TYPE=float
FORECAST_PROVIDER=solcast
FORECAST_CONFIGURATIONS=1
FORECAST_INTERVAL=900
INFLUX_MEASUREMENT_FORECAST=forecast
FORECAST_LATITUDE=47.73128
FORECAST_LONGITUDE=12.45895
FORECAST_DECLINATION=33
FORECAST_AZIMUTH=-75
FORECAST_KWP=11.4
INFLUX_HOST=influxdb
INFLUX_SCHEMA=http
INFLUX_PORT=8086
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=...
INFLUX_ADMIN_TOKEN=...
INFLUX_BUCKET=solectrus
INFLUX_TOKEN_WRITE=...
INFLUX_TOKEN_READ=...
INFLUX_VOLUME_PATH=/SSD/appdata/solectrus/influxdb
DB_VOLUME_PATH=/SSD/appdata/solectrus/postgresql
REDIS_VOLUME_PATH=/SSD/appdata/solectrus/redis
REDIS_URL=redis://redis:6379/1
```
