### DISCUSSION TITLE
Zwei verschiedene Dachflächen werden nicht angezeigt

### DISCUSSION THREAD

**Discussion by Opa62** [solectrus/solectrus#4278] [Q&A] [answered]
Hallo Georg,

ich habe jetzt mal die .evn und die Yaml angepasst, das meine zwei Dachflächen (Hausdach, Garagendach) extra angezeigt werden, 
leider haut es nicht hin, bei Aktuell bekomme ich die alte Anzeige, bei den weiteren Reitern Tag Woche usw. kommt die Fehlermeldung:
500 Interner Server-Fehler ?? Bei den Einstellungen wird der Reiter Sensoren angezeigt.
Ein Balkonkraftwerk habe ich nicht.
Ich habe mal die .env und die yaml mit eingefügt,
wo habe ich einen Fehler gemacht oder was falsches eingetragen??
schon mal Danke für die Hilfe.

compose.yaml:

```yaml
services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:pr-4151
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3222:3000
    environment:
      - TZ
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - UI_THEME
      - CO2_EMISSION_FACTOR
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER    
      - INFLUX_SENSOR_INVERTER_POWER_1
      - INFLUX_SENSOR_INVERTER_POWER_2
      - INFLUX_SENSOR_INVERTER_POWER_3
      - INFLUX_SENSOR_INVERTER_POWER_4
      - INFLUX_SENSOR_INVERTER_POWER_5
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_CAR_BATTERY_SOC
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - TZ
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  postgresql:
    image: postgres:16-alpine
    environment:
      - TZ
      - POSTGRES_PASSWORD
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  redis:
    image: redis:7-alpine
    environment:
      - TZ
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  senec-collector:
    image: ghcr.io/solectrus/senec-collector:latest
    environment:
      - TZ
      - SENEC_ADAPTER
      - SENEC_HOST
      - SENEC_SCHEMA
      - SENEC_INTERVAL
      - SENEC_LANGUAGE
      - SENEC_USERNAME
      - SENEC_PASSWORD
      - SENEC_IGNORE
      - SENEC_SYSTEM_ID
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SENEC}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  shelly-collector:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST
      - SHELLY_CLOUD_SERVER
      - SHELLY_AUTH_KEY
      - SHELLY_DEVICE_ID
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  shelly-collector-waschmaschine:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST=${SHELLY_HOST_WASCHMASCHINE}
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY_WASCHMASCHINE}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  shelly-collector-trocknergefrierschrank:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST=${SHELLY_HOST_TROCKNERGEFRIERSCHRANK}
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY_TROCKNERGEFRIERSCHRANK}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest
    environment:
      - TZ
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - MAPPING_0_TOPIC
      - MAPPING_0_MEASUREMENT
      - MAPPING_0_FIELD
      - MAPPING_0_TYPE
      - MAPPING_1_TOPIC
      - MAPPING_1_MEASUREMENT
      - MAPPING_1_FIELD
      - MAPPING_1_TYPE
      - MAPPING_2_TOPIC
      - MAPPING_2_MEASUREMENT
      - MAPPING_2_FIELD
      - MAPPING_2_TYPE
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    environment:
      - TZ
      - FORECAST_PROVIDER
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_CONFIGURATIONS
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_3_DECLINATION
      - FORECAST_3_AZIMUTH
      - FORECAST_3_KWP
      - FORECAST_INTERVAL
      - FORECAST_SOLAR_APIKEY
      - FORECAST_DAMPING_MORNING
      - FORECAST_DAMPING_EVENING
      - FORECAST_HORIZON
      - FORECAST_INVERTER
      - SOLCAST_APIKEY
      - SOLCAST_SITE
      - SOLCAST_0_SITE
      - SOLCAST_1_SITE
      - INFLUX_HOST
      - INFLUX_PORT
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_FORECAST}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:latest
    environment:
      - TZ
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL
      - POWER_SPLITTER_INTERVAL
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope solectrus --cleanup
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```

.evn:

```env
##################################################################
###                          Generic                           ###
##################################################################

TZ=Europe/Berlin

##################################################################
###                   Dashboard application                    ###
##################################################################

# Domain name or IP address of your host
APP_HOST=........................

# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2023-02-24

# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=............................

# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false

# Secret token to secure cookies, 128 chars long hexadecimal encoded string
SECRET_KEY_BASE=0bb56ba2a9e4abdd1590ba68bbac4a971e238f79600e2a6a7e99ac4a3392dc6285a090f0ff283f6594db3c402fef97a6e802ab93eca859c108a6ea36e4d29c7e

# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0

# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com

# Optional: Set factor to calculate CO2 emissions (default: 401 g/kWh)
# CO2_EMISSION_FACTOR=500

# Password for the PostgreSQL database, used by the app to communicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to connect to the database!
POSTGRES_PASSWORD=my-secret-db-password

##################################################################
###                      Sensor mapping                        ###
##################################################################

# Where to find the data in the InfluxDB
# Each sensor must be mapped to a measurement and a field
# The format is: INFLUX_SENSOR_NAME=MEASUREMENT:FIELD
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power

INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_INVERTER_POWER_1=Erzeugung-SENEC:Hausdach
INFLUX_SENSOR_INVERTER_POWER_2=Erzeugung-SENEC:Garagendach
INFLUX_SENSOR_INVERTER_POWER_3= # Erzeugung 3, falls bekannt
INFLUX_SENSOR_INVERTER_POWER_4= # Erzeugung 4, falls bekannt
INFLUX_SENSOR_INVERTER_POWER_5= # Erzeugung 5, falls bekannt
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
INFLUX_SENSOR_WALLBOX_POWER=pv:wallbox_power
INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=pv:car_connected
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_INVERTER_POWER_FORECAST=forecast:watt
INFLUX_SENSOR_HEATPUMP_POWER=heatpump:power
INFLUX_SENSOR_CAR_BATTERY_SOC=car:battery_soc
INFLUX_SENSOR_CUSTOM_POWER_01=Ladegereate:power
INFLUX_SENSOR_CUSTOM_POWER_02=Nasraspberry:power
INFLUX_SENSOR_CUSTOM_POWER_03=Fernseher:power
INFLUX_SENSOR_CUSTOM_POWER_04=TrocknerGefrierschrank:power
INFLUX_SENSOR_CUSTOM_POWER_05=Waschmaschine:power

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER,WALLBOX_POWER

##################################################################
###                      SENEC Collector                       ###
##################################################################

# The adapter to use
# Values: local, cloud
SENEC_ADAPTER=local

# The IP address or hostname of your SENEC device
# Available only when using the local adapter
SENEC_HOST=192.168.178.90

# The schema protocol to use
# Available only when using the local adapter
# Values: http, https
SENEC_SCHEMA=https

# The language to use for status strings
# Available only when using the local adapter
# Values: de, en, it
SENEC_LANGUAGE=de

# The credentials for mein-senec.de
# Available only when using the cloud adapter
# SENEC_USERNAME=me@example.com
# SENEC_PASSWORD=my-senec-password

# The system ID of your SENEC device
# Available only when using the cloud adapter
# Can be empty if there is just one system
# SENEC_SYSTEM_ID=123456

# The interval in seconds for polling
# Minimum for local adapter is 5 seconds
# Minimum for cloud adapter is 30 seconds
SENEC_INTERVAL=5

# Measurement name for InfluxDB
INFLUX_MEASUREMENT_SENEC=SENEC

# Optional: Disable specific fields you do not want to send to InfluxDB.
# This can be useful if you are tracking them from another source.
# Comma separated list of fields, no whitespace. Example:
SENEC_IGNORE=wallbox_charge_power

##################################################################
###                     Shelly Collector                       ###
##################################################################

# IP of your Shelly device
SHELLY_HOST=..................

# Alternative use the Shelly cloud:
# Get Server, Auth_Key and device_id from https://control.shelly.cloud
#
# SHELLY_CLOUD_SERVER=https://shelly-42-eu.shelly.cloud
# SHELLY_AUTH_KEY=the-long-auth-key
# SHELLY_DEVICE_ID=12345abcdef0

# Interval in seconds to get data from Shelly
SHELLY_INTERVAL=5

# Measurement name for InfluxDB
INFLUX_MEASUREMENT_SHELLY=heatpump

##################################################################
###                       MQTT Collector                       ###
##################################################################

##### MQTT Broker credentials
MQTT_HOST=..............
MQTT_PORT=1883
MQTT_SSL=false
MQTT_USERNAME=anton
MQTT_PASSWORD=Topspin17090917

##### Mappings

# Index of the mappings, starting with 0
# Example:
#
# MAPPING_0_TOPIC=example-device/0/ENERGY/INVERTER_POWER
# MAPPING_0_MEASUREMENT=EXAMPLE
# MAPPING_0_FIELD=inverter_power
# MAPPING_0_TYPE=integer # One of integer, float, string, boolean
#
# MAPPING_1_TOPIC=example-device/0/ENERGY/BAT_CHARGE_POWER
# MAPPING_1_MEASUREMENT=EXAMPLE
# MAPPING_1_FIELD=battery_charging_power
# MAPPING_1_TYPE=float
#
# ...
MAPPING_0_TOPIC=evcc/loadpoints/1/chargePower
MAPPING_0_MEASUREMENT=pv
MAPPING_0_FIELD=wallbox_power
MAPPING_0_TYPE=integer
MAPPING_1_TOPIC=evcc/loadpoints/1/connected
MAPPING_1_MEASUREMENT=pv
MAPPING_1_FIELD=car_connected
MAPPING_1_TYPE=string
MAPPING_2_TOPIC=evcc/loadpoints/1/vehicleSoc
MAPPING_2_MEASUREMENT=car
MAPPING_2_FIELD=battery_soc
MAPPING_2_TYPE=float

##################################################################
###                       Power Splitter                       ###
##################################################################

# Interval in seconds to run the calculation (default: 3600, min: 300)
# POWER_SPLITTER_INTERVAL=3600

##################################################################
###                     Forecast collector                     ###
##################################################################

FORECAST_PROVIDER=solcast

# Number of planes (if you have more than one). Default is 1. Forecast.solar allows up to 4 planes, Solcast up to 2.
FORECAST_CONFIGURATIONS=1

# Update interval in seconds
FORECAST_INTERVAL=8640

# Measurement name for InfluxDB
INFLUX_MEASUREMENT_FORECAST=forecast

### Details for forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate

# Latitude of the plant location
# FORECAST_LATITUDE=50.12345

# Longitude of the plant location
# FORECAST_LONGITUDE=6.12345

# Plane declination: 0 (horizontal) - 90 (vertical)
# FORECAST_DECLINATION=30

# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
# FORECAST_AZIMUTH=20

# Installed modules power in kilowatt peak (kWp)
# FORECAST_KWP=8.4

# Optional damping factors (http://doc.forecast.solar/damping)
# FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional configuration for multiple planes
#
# Starting from 0, add params different from the values defined above
# FORECAST_0_DECLINATION=35
# FORECAST_0_AZIMUTH=-180
# FORECAST_0_KWP=5.32
#
# FORECAST_1_DECLINATION=38
# FORECAST_1_AZIMUTH=-90
# FORECAST_1_KWP=5.32
#
# FORECAST_2_DECLINATION=50
# FORECAST_2_AZIMUTH=0
# FORECAST_2_KWP=7.84
#
# FORECAST_3_DECLINATION=50
# FORECAST_3_AZIMUTH=90
# FORECAST_3_KWP=2.58
#
# Available params are:
# - FORECAST_x_LATITUDE
# - FORECAST_x_LONGITUDE
# - FORECAST_x_DECLINATION
# - FORECAST_x_AZIMUTH
# - FORECAST_x_KWP
# - FORECAST_x_DAMPING_MORNING
# - FORECAST_x_DAMPING_EVENING

# Optional API key for registered users of forecast.solar (https://doc.forecast.solar/account_models)
# FORECAST_SOLAR_APIKEY=abc123

### Details for solcast.com

SOLCAST_APIKEY=hTkccPfXDvrl0iMolObxAAa78PvObs2P
SOLCAST_SITE=1111-2222-3333-4444

SOLCAST_0_SITE=b219-90e4-09da-a20a
# SOLCAST_1_SITE=5555-6666-7777-8888

##################################################################
###                 InfluxDB time series database              ###
##################################################################

# InfluxDB host
INFLUX_HOST=influxdb

# InfluxDB schema (http or https)
INFLUX_SCHEMA=http

# InfluxDB port
INFLUX_PORT=8086

# Credentials for the InfluxDB, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=ExAmPl3PA55W0rD
INFLUX_ADMIN_TOKEN=my-super-secret-admin-token

# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=solectrus

# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=my-super-secret-admin-token
INFLUX_TOKEN_READ=my-super-secret-admin-token

# Volume path for storing the InfluxDB data
INFLUX_VOLUME_PATH=/volume1/docker/solectrus/influxdb

##################################################################
###                    PostgreSQL database                     ###
##################################################################

# Volume path for storing the PostgreSQL data
DB_VOLUME_PATH=/volume1/docker/solectrus/postgresql

##################################################################
###                 Redis in-memory database                   ###
##################################################################

# Volume path for storing the database snapshot
REDIS_VOLUME_PATH=/volume1/docker/solectrus/redis

# URL of the Redis database
REDIS_URL=redis://redis:6379/1
```
