### DISCUSSION TITLE
Komfortabel Docker-Logs einsehen mit Dozzle

### DISCUSSION THREAD

**Discussion by ledermann** [solectrus/solectrus#4299] [Show and tell]
Das Einsehen der Logs, die von den verschiedenen SOLECTRUS-Docker-Containern produziert werden, ist nicht jedermanns Sache. Wer mit der Kommandozeile sowieso auf Kriegsfuß steht, schaut tendenziell eher nicht in die Logs ;-)

Kürzlich bin ich auf ein interessantes Tool gestoßen, das nützlich ist, wenn man SOLECTRUS auf einem einfachen Docker-Host betreibt und nicht sowieso bereits zusätzliche Werkzeuge wie Portainer, Dockge, Komodo o.ä. benutzt:

Mit [Dozzle](https://dozzle.dev/) lassen sich die Container auf einfachste Weise überwachen und insbesondere die Logs einsehen und durchsuchen - und zwar direkt über den Browser. Und da sich Dozzle extrem einfach installieren lässt, möchte ich das hier empfehlen.

![dozzle](https://github.com/user-attachments/assets/2b633631-1459-42eb-80fc-87d85a88c539)

Das einzige, was zur Installation erforderlich ist, ist die Ergänzung folgender Zeilen in die bestehende `compose.yaml` (bzw. `docker-compose.yml`):

```yaml
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```

(Bitte wie immer auf die richtige Einrückung achten!)

Danach muss nur noch ein `docker compose up -d` erfolgen und Dozzle steht unter folgender Adresse bereit:

`http://[raspberry-ip]:8080`

> [!NOTE]  
> Dozzle ermöglicht den Zugriff auf die Docker-Container über den Browser. In den Logs stehen möglicherweise sensible Informationen. Daher sollte man sich zusätzliche Gedanken über Zugriffsberechtigungen machen, wenn der eigene Docker-Host aus dem Internet erreichbar ist. Dozzle bietet dafür auch [Unterstützung](https://dozzle.dev/guide/authentication), aber dann ist es nicht mehr ganz so einfach zu installieren. Wer SOLECTRUS auf einem nur lokal erreichbaren Host betreibt (das dürften die meisten sein), der kann Dozzle auch problemlos ohne Authentifizierung betreiben.

> [!WARNING]  
> Dozzle greift über die Socket-Schnittstelle auf den Docker-Host zu und hat damit weitreichende Möglichkeiten und quasi Vollzugriff auf den Host. Dies erfordert ein gewisses Vertrauen in die Software.
