### ISSUE TITLE
Wärmepumpe mit MQTT konfigurieren

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#3051]
_Originally posted by @halmich in https://github.com/solectrus/solectrus/discussions/2861#discussioncomment-9243848_

> ich versuche gerade auch meine Wärmepumpe über MQTT in Solectrus zu bekommen.
>
> den mqtt collector habe ich in docker-compose.yml eingefügt (Datei ist unten angefügt)
Dabei musste ich allerdings `service_unhealty` auskommentieren. 
Außerdem musste ich noch `env_file: .env` hinzufügen. ist das richtig so?
>
> In der .env Datei habe ich die credentials gesetzt und nur das Topic angegeben.
>
> Im MQTT Log erscheint jedoch dauernd:
>
> `Error while pushing to InfluxDB: unable to parse 'heatpump_power=3i 1714204074': invalid field format`
>
> Hat jemand eine Idee was nicht läuft?
> Macht es Sinn den Konfigurator zu nutzen und die .env Datei sowie die docker-compose.yml komplett neu aufzubauen?

```
mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:develop
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      - influxdb
       # condition: service_healthy
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_PV}
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
#      - MQTT_TOPIC_HOUSE_POW
#      - MQTT_TOPIC_GRID_POW
#      - MQTT_TOPIC_BAT_CHARGE_CURRENT
#      - MQTT_TOPIC_BAT_FUEL_CHARGE
#      - MQTT_TOPIC_BAT_POWER
#      - MQTT_TOPIC_BAT_VOLTAGE
#      - MQTT_TOPIC_CASE_TEMP
#      - MQTT_TOPIC_CURRENT_STATE
#      - MQTT_TOPIC_MPP1_POWER
#      - MQTT_TOPIC_MPP2_POWER
#      - MQTT_TOPIC_MPP3_POWER
#      - MQTT_TOPIC_INVERTER_POWER
     # - MQTT_TOPIC_WALLBOX_CHARGE_POWER
#      - MQTT_FLIP_BAT_POWER
      - MQTT_HEATPUMP_POWER
    env_file: .env
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'
```

```
# MQTT Collector

# MQTT Broker credentials
MQTT_HOST=192.168.178.53
MQTT_PORT=1883
MQTT_SSL=false
MQTT_USERNAME=test
MQTT_PASSWORD=test

# MQTT topics
# https://docs.evcc.io/docs/reference/api#mqtt-api
#MQTT_TOPIC_HOUSE_POW=evcc/site/homePower
#MQTT_TOPIC_GRID_POW=evcc/site/gridPower
#MQTT_TOPIC_BAT_FUEL_CHARGE=evcc/site/batterySoc
#MQTT_TOPIC_BAT_POWER=evcc/site/batteryPower
#MQTT_TOPIC_INVERTER_POWER=evcc/site/pvPower
#MQTT_TOPIC_WALLBOX_CHARGE_POWER=evcc/loadpoints/1/chargePower
MQTT_TOPIC_HEATPUMP_POWER=controller/ccp
# MQTT options
#MQTT_FLIP_BAT_POWER=true
```

> Ich habe eben den Konfigurator ausprobiert, dann kommt jedoch folgende Fehlermeldung und der container solectrus-postgresql-1 startet nicht
>
> Edit: hab in der .yml Datei v15 anstatt 16 eingetragen. damit startet der Container wieder.
Kann ich irgendwie auf 16 upgraden?

```
postgresql-1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgresql-1          |
postgresql-1          | 2024-04-27 08:08:45.589 UTC [1] FATAL:  database files are incompatible with server
postgresql-1          | 2024-04-27 08:08:45.589 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.2.
```

**Comment by halmich** [comment]
Noch eine Frage:
Ich habe den Konfigurator benutzt und angegeben, dass ich einen v2.1 und zusätzlich die Wärmepumpe über MQTT auslese.
In der .env und in der .yml tauchen jedoch keine Parameter / Credentials zu MQTT auf.
Ist das ein Bug?

**Comment by ledermann** [comment]
Hier gibt es einen ganzen Schwung verschiedener Probleme, die sich aber alle lösen lassen :-)

1) Wenn ein Container `unhealthy` ist, dann bitte unbedingt ins Log dieses Containers gucken, was da falsch läuft. Das geht z.B. mit `docker compose logs influxdb`. Je nachdem, was dort steht, muss dieses Problem behoben werden. Es ist **nicht** empfehlenswert, das `condition: service_healthy` auszubauen.

2) Wenn einer der Container redis, postgresql oder influxdb ungesund ist, ist das ein schlechtes Zeichen, das hat dann auch nichts mit SOLECTRUS zu tun. Vor allen anderen Schritte sollte das geklärt werden. Die drei Datenbank-Container müssen auf fehlerfrei laufen.

3) Zu PostgreSQL: Neuer Major-Versionen können nicht die Daten der Vorgängerversion lesen, die müssen migriert werden. Version 16 kann also nicht die Daten der Version 15 lesen. Da das Migrieren etwas fummelig ist, lass das besser erst mal weg. Wenn du also bislang `postgres:15-alpine` verwendet hast, dann darf nicht einfach auf `postgres:16-alpine` gewechselt werden.

4) An die Logs des MQTT-Collectors kommst du analog: mit `docker compose logs mqtt-collector`

5) Den Konfigurator lasse besser auch erst mal weg, der ist noch unfertig. Den beschriebenen Fehler, dass der MQTT-Collector nicht in .env und compose.yml auftaucht, kann ich zwar nicht reproduzieren, meinen Tests zufolge klappt das, aber etwaige Fehler im Konfigurator behandeln wir besser separat.

6) Der Eintrag `env_file: .env` sollte nicht erforderlich sein. Was passiert, wenn du das weglässt?

7) Die Fehlermeldung `heatpump_power=3i 1714204074': invalid field format` resultiert vermutlich aus einem Datentyp-Konflikt. Integer-Werte können nicht in ein Float-Field geschrieben werden.

8) Etwaige Fehler im Konfigurator behandeln wir besser separat, sonst ufert das hier wirklich aus :)

Um der Sache genauer auf den Grund zu gehen: Gib mir bitte mal die beiden vollständigen Dateien `.env` und `compose.yml` - Passwörter und andere heikle Angaben vorher anonymisieren. Dann werde ich das hier nachstellen.

**Comment by halmich** [comment]
auch hier noch kurze als Antwort für Mitlesende:

zu 1/2: ohne Auskommentierung erscheint beim Startes der Container: `Dependency failed do start: container solectrus-influxdb-1 has no healtcheck configured`
Aus meiner Sicht ist die Datenbank aber intakt.

3/4: alles klar, bin wieder auf 15.

5: Zum Nachstellen. Konfigurator aufrufen.
Haken bei Solarwechselrichter, Speicher, Wärmepumpe
Stromspeicher: v3/2.1
Wärmepumpe über MQTT
Lokal
RaspberyPi
ip: egal
Ip: egal, alle Werte lassen
Ip egal, port 1883, benutzername: meinBenutzer: Passwort: MeinPasswort

MQTT Topics:
bei Wärmepumpe: controller/ccp  , Verbrauch ist im Hausverbrauch enthalten. ansonsrten alles leer.
Prognose: nein
AWS: nein
Inbetriebnahme und PW: egal

Abschließen.
In beiden Dateien ist kein Hinweis zu MQTT.

Zu 6: wenn der eintrag nicht gesetzt ist, fragt MQTT keine Werte ab.

Zu 7: ok, da muss ich schauen, ob ich das Lösen kann.



compose.yml
```
services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:next
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - postgresql
      - influxdb
      - redis
    ports:
      - '3000:3000'
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  postgresql:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  redis:
    image: redis:7-alpine
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  senec-collector:
    image: ghcr.io/solectrus/senec-collector:latest
    environment:
      - SENEC_ADAPTER
      - SENEC_HOST
      - SENEC_SCHEMA
      - SENEC_INTERVAL
      - SENEC_LANGUAGE
      - SENEC_USERNAME
      - SENEC_PASSWORD
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${SENEC_INFLUX_MEASUREMENT}
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: '--scope solectrus --cleanup'
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```
```

##################################################################
###                   Dashboard application                    ###
##################################################################

# Domain name or IP address of your host
APP_HOST=eeee

# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2024-04-03

# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=sdfsfsf

# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false

# Secret token to secure cookies, 128 chars long hexadecimal encoded string
SECRET_KEY_BASE=80db24c899ba24e501012a64c7d14ee24628bcf35fc1435c5aa18af27754f53024cd3766e3f583a4d7e87a47fdcfaf2e0e7ae6a2128ef5e39373565e85d85b96

# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0

# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com

# Password for the PostgreSQL database, used by the app to comunicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to connect to the database!
POSTGRES_PASSWORD=my-secret-db-password

##################################################################
###                      Sensor mapping                        ###
##################################################################

# Where to find the data in the InfluxDB
# Each sensor must be mapped to a measurement and a field
# The format is: INFLUX_SENSOR_NAME=MEASUREMENT:FIELD
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power

INFLUX_SENSOR_INVERTER_POWER=senec:inverter_power
INFLUX_SENSOR_HOUSE_POWER=senec:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=senec:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=senec:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=senec:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=senec:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=senec:bat_fuel_charge
# INFLUX_SENSOR_WALLBOX_POWER=
INFLUX_SENSOR_CASE_TEMP=senec:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=senec:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=senec:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=senec:power_ratio
# INFLUX_SENSOR_INVERTER_POWER_FORECAST=
INFLUX_SENSOR_HEATPUMP_POWER=heatpump:power

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER

##################################################################
###                      SENEC Collector                       ###
##################################################################

# The adapter to use
# Values: local, cloud
SENEC_ADAPTER=local

# The IP address or hostname of your SENEC device
# Available only when using the local adapter
SENEC_HOST=ffff

# The schema protocol to use
# Available only when using the local adapter
# Values: http, https
SENEC_SCHEMA=https

# The language to use for status strings
# Available only when using the local adapter
# Values: de, en, it
SENEC_LANGUAGE=de

# The credentials for mein-senec.de
# Available only when using the cloud adapter
# SENEC_USERNAME=me@example.com
# SENEC_PASSWORD=my-senec-password

# The system ID of your SENEC device
# Available only when using the cloud adapter
# Can be empty if there is just one system
# SENEC_SYSTEM_ID=123456

# The interval in seconds for polling
# Minimum for local adapter is 5 seconds
# Minimum for cloud adapter is 30 seconds
SENEC_INTERVAL=5

# Measurement name for InfluxDB
SENEC_INFLUX_MEASUREMENT=senec

# Optional: Disable specific fields you do not want to send to InfluxDB.
# This can be useful if you are tracking them from another source.
# Comma separated list of fields, no whitespace. Example:
# SENEC_IGNORE=wallbox_charge_power,grid_power_minus

##################################################################
###                 InfluxDB time series database              ###
##################################################################

# InfluxDB host
INFLUX_HOST=influxdb

# InfluxDB schema (http or https)
INFLUX_SCHEMA=http

# InfluxDB port
INFLUX_PORT=8086

# Credentials for the InfluxDB, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=ExAmPl3PA55W0rD
INFLUX_ADMIN_TOKEN=my-super-secret-admin-token

# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=solectrus

# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=my-super-secret-admin-token
INFLUX_TOKEN_READ=my-super-secret-admin-token

# Volume path for storing the InfluxDB data
INFLUX_VOLUME_PATH=./influxdb

##################################################################
###                    PostgreSQL database                     ###
##################################################################

# Volume path for storing the PostgreSQL data
DB_VOLUME_PATH=./postgresql

##################################################################
###                 Redis in-memory database                   ###
##################################################################

# Volume path for storing the database snapshot
REDIS_VOLUME_PATH=./redis
```
