### ISSUE TITLE
Nach Update sind Wochen-/Monats-Diagramme durcheinander

### ISSUE THREAD

**Issue by frizzle0815** [solectrus/solectrus#3311]
### Description (in German or English)

Solectrus hat sich am 30.07. auf die neuste develop-Version aktualisiert. Redis wurde auch aktualisiert.
Seitdem ist irgendetwas mit den Wochen- und Monats-Übersicht durcheinander. Für die Jahresübersicht kann ich es schlecht verifzieren. Die Tagesansicht funktioniert anscheinend ganz normal.

"Erzeugung":
- Werte bis 29.07. sind konsistent und vollständig
- Werte ab 30.07. sind in der Wochen- und Monats-Ansicht leer (bzw. 30.07. zeigt einen minimalen Wert an, vielleicht bis zum Zeitpunkt des Updates)

"Netz"
- Werte bis 29.07. sind konsistent und vollständig
- Werte ab 30.07. werden in der Wochen-Ansicht angezeigt, in der Monats-Ansicht aber gar nicht.

"Haus-Verbrauch"
- Werte bis 29.07. sind konsistent und vollständig
- Werte ab 30.07. scheinen auch zu passen
- Werte am 31.07. (heute) Tag zeigt 6,8 kWh, Woche 7,251 kWh, Monat 7,298 kWh (immerhin ist hier für Monat aber ein Wert vorhanden)

"Akku"
- Werte bis 29.07. sind konsistent und vollständig
- Werte am 30.07. Tag zeigt Entl. 7,7+Bel. 7,9, passt aber nicht zu: Woche+Monat: Bel. 7,9+Entl 5,092
- Werte am 31.07. (heute) werden in Woche/Monat gar nicht angezeigt

"Co2 Reduktion"
Keine Werte in Wochen-/Monats-Ansicht ab 30.07.

Normal zu funktionieren scheint "Ladestand", "Autarkie", "Verbrauch". Temperatur erfasse ich nicht und das E-Auto wurde seit 30.07. nicht geladen, weshalb ich dazu auch nichts sagen kann...

### What version of SOLECTRUS are you using?

v0.15.0-71-g9d346cdg

### What machine are you running SOLECTRUS on?

Synology

### Please provide your `docker-compose.yml` or `compose.yml` file

```yaml
services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:develop
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - postgresql
      - influxdb
      - redis
    ports:
      - 3000:3000
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  postgresql:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  redis:
    image: redis:7-alpine
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:develop
    environment:
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - MAPPING_0_TOPIC
      - MAPPING_0_MEASUREMENT
      - MAPPING_0_FIELD
      - MAPPING_0_TYPE
      - MAPPING_1_TOPIC
      - MAPPING_1_MEASUREMENT
      - MAPPING_1_FIELD
      - MAPPING_1_TYPE
      - MAPPING_2_TOPIC
      - MAPPING_2_MEASUREMENT_POSITIVE
      - MAPPING_2_MEASUREMENT_NEGATIVE
      - MAPPING_2_FIELD_POSITIVE
      - MAPPING_2_FIELD_NEGATIVE
      - MAPPING_2_TYPE
      - MAPPING_3_TOPIC
      - MAPPING_3_MEASUREMENT_POSITIVE
      - MAPPING_3_MEASUREMENT_NEGATIVE
      - MAPPING_3_FIELD_POSITIVE
      - MAPPING_3_FIELD_NEGATIVE
      - MAPPING_3_TYPE
      - MAPPING_4_TOPIC
      - MAPPING_4_MEASUREMENT
      - MAPPING_4_FIELD
      - MAPPING_4_TYPE
      - MAPPING_5_TOPIC
      - MAPPING_5_MEASUREMENT
      - MAPPING_5_FIELD
      - MAPPING_5_TYPE
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:develop
    environment:
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_CONFIGURATIONS
      - FORECAST_0_LATITUDE
      - FORECAST_0_LONGITUDE
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_0_DAMPING_MORNING
      - FORECAST_0_DAMPING_EVENING
      - FORECAST_1_LATITUDE
      - FORECAST_1_LONGITUDE
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_1_DAMPING_MORNING
      - FORECAST_1_DAMPING_EVENING
      - FORECAST_2_LATITUDE
      - FORECAST_2_LONGITUDE
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_2_DAMPING_MORNING
      - FORECAST_2_DAMPING_EVENING
      - FORECAST_3_LATITUDE
      - FORECAST_3_LONGITUDE
      - FORECAST_3_DECLINATION
      - FORECAST_3_AZIMUTH
      - FORECAST_3_KWP
      - FORECAST_3_DAMPING_MORNING
      - FORECAST_3_DAMPING_EVENING
      - FORECAST_INTERVAL
      - FORECAST_SOLAR_APIKEY
      - INFLUX_HOST
      - INFLUX_PORT
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${FORECAST_INFLUX_MEASUREMENT}
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope solectrus --cleanup
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```

### Please provide your `.env` file

```text
APP_HOST=192.168.2.50
INSTALLATION_DATE=2024-06-12
ADMIN_PASSWORD=xxxxxx
INFLUX_POLL_INTERVAL=5
FORCE_SSL=false
SECRET_KEY_BASE=xxxxx
WEB_CONCURRENCY=0
POSTGRES_PASSWORD=my-secret-db-password
INFLUX_SENSOR_INVERTER_POWER=pv:inverter_power
INFLUX_SENSOR_HOUSE_POWER=pv:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=pv:grid_import_power
INFLUX_SENSOR_GRID_EXPORT_POWER=pv:grid_export_power
INFLUX_SENSOR_BATTERY_CHARGING_POWER=pv:battery_charging_power
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=pv:battery_discharging_power
INFLUX_SENSOR_BATTERY_SOC=pv:battery_soc
INFLUX_SENSOR_WALLBOX_POWER=pv:wallbox_power
INFLUX_SENSOR_CASE_TEMP=pv:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=pv:system_status
INFLUX_SENSOR_SYSTEM_STATUS_OK=pv:system_status_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=pv:grid_export_limit
INFLUX_SENSOR_INVERTER_POWER_FORECAST=forecast:watt
INFLUX_EXCLUDE_FROM_HOUSE_POWER=WALLBOX_POWER
MQTT_HOST=192.168.2.50
MQTT_PORT=1883
MQTT_SSL=false
MQTT_USERNAME=xxxxx
MQTT_PASSWORD=xxxxx
MAPPING_0_TOPIC=solectrus/erzeugung
MAPPING_0_MEASUREMENT=pv
MAPPING_0_FIELD=inverter_power
MAPPING_0_TYPE=integer
MAPPING_1_TOPIC=solectrus/hausverbrauch
MAPPING_1_MEASUREMENT=pv
MAPPING_1_FIELD=house_power
MAPPING_1_TYPE=integer
MAPPING_2_TOPIC=solectrus/netzbezug
MAPPING_2_MEASUREMENT_POSITIVE=pv
MAPPING_2_MEASUREMENT_NEGATIVE=pv
MAPPING_2_FIELD_POSITIVE=grid_import_power
MAPPING_2_FIELD_NEGATIVE=grid_export_power
MAPPING_2_TYPE=integer
MAPPING_3_TOPIC=solectrus/batterie
MAPPING_3_MEASUREMENT_POSITIVE=pv
MAPPING_3_MEASUREMENT_NEGATIVE=pv
MAPPING_3_FIELD_POSITIVE=battery_charging_power
MAPPING_3_FIELD_NEGATIVE=battery_discharging_power
MAPPING_3_TYPE=integer
MAPPING_4_TOPIC=solectrus/batterie_soc
MAPPING_4_MEASUREMENT=pv
MAPPING_4_FIELD=battery_soc
MAPPING_4_TYPE=float
MAPPING_5_TOPIC=openWB/chargepoint/get/power
MAPPING_5_MEASUREMENT=pv
MAPPING_5_FIELD=wallbox_power
MAPPING_5_TYPE=integer
FORECAST_LATITUDE=xxxx
FORECAST_LONGITUDE=xxxx
FORECAST_CONFIGURATIONS=3
FORECAST_0_DECLINATION=18
FORECAST_0_AZIMUTH=20
FORECAST_0_KWP=5.34
FORECAST_1_DECLINATION=18
FORECAST_1_AZIMUTH=110
FORECAST_1_KWP=6.23
FORECAST_2_DECLINATION=15
FORECAST_2_AZIMUTH=20
FORECAST_2_KWP=2.67
FORECAST_INTERVAL=2700
FORECAST_INFLUX_MEASUREMENT=forecast
FORECAST_INVERTER=10.0
INFLUX_HOST=influxdb
INFLUX_SCHEMA=http
INFLUX_PORT=8086
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=ExAmPl3PA55W0rD
INFLUX_ADMIN_TOKEN=my-super-secret-admin-token
INFLUX_BUCKET=solectrus
INFLUX_TOKEN_WRITE=my-super-secret-admin-token
INFLUX_TOKEN_READ=my-super-secret-admin-token
INFLUX_VOLUME_PATH=/volume1/docker/solectrus/influxdb
DB_VOLUME_PATH=/volume1/docker/solectrus/postgresql
REDIS_VOLUME_PATH=/volume1/docker/solectrus/redis
```
