### ISSUE TITLE
TypeError bei Zeiträumen

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#3752]
Beschrieben von @Zeppelin-PV in #3749:

> Meine ersten zwei Verbraucher werden angezeigt, allerdings nur im Aktuell
> Tag, Woche, etc. kommt Fehler 500

### Welche Version von SOLECTRUS verwendest du?

custom-consumers-63

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Raspi 4

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text
dashboard-1 | I, [2024-12-06T21:12:29.171896 #1] INFO -- : [192.168.1.110] method=GET path=/house/stats/custom_power_02/2024-12-06
format=html controller=House::StatsController action=index status=500 allocations=51866 duration=946.73 view=0.00 db=67.31
dashboard-1 | E, [2024-12-06T21:12:29.184009 #1] ERROR -- : [192.168.1.110]
dashboard-1 | [192.168.1.110] ActionView::Template::Error (nil can't be coerced into Float):
dashboard-1 | [192.168.1.110]
dashboard-1 | Causes:
dashboard-1 | [192.168.1.110] TypeError (nil can't be coerced into Float)
dashboard-1 | [192.168.1.110] 53:
dashboard-1 | [192.168.1.110] 54: // Inner content
dashboard-1 | [192.168.1.110] 55: .flex-1.flex
dashboard-1 | [192.168.1.110] 56: = render SegmentContainer::Component.new tippy_placement: 'right',
dashboard-1 | [192.168.1.110] 57: calculator:,
dashboard-1 | [192.168.1.110] 58: timeframe: do |balance|
dashboard-1 | [192.168.1.110] 59: ruby:
dashboard-1 | [192.168.1.110]
dashboard-1 | [192.168.1.110] app/services/calculator/range.rb:328:in `*'
dashboard-1 | [192.168.1.110] app/services/calculator/range.rb:328:in `block (2 levels) in <class:Range>'
dashboard-1 | [192.168.1.110] app/components/segment/component.rb:67:in `public_send'
dashboard-1 | [192.168.1.110] app/components/segment/component.rb:67:in `costs'
dashboard-1 | [192.168.1.110] app/components/segment/component.html.slim:65:in `block in call'
dashboard-1 | [192.168.1.110] app/components/segment/component.html.slim:15:in `call'
dashboard-1 | [192.168.1.110] app/components/segment_container/component.html.slim:5:in `block in call'
dashboard-1 | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `each'
dashboard-1 | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `call'
dashboard-1 | [192.168.1.110] app/views/house/stats/index.turbo_stream.slim:56
dashboard-1 | [192.168.1.110] app/controllers/house/stats_controller.rb:8:in `index'
dashboard-1 | [192.168.1.110] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
```

### Dein vollständiges `docker-compose.yml` oder `compose.yml`

```yaml
services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:pr-3747
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - postgresql
      - influxdb
      - redis
    ports:
      - 3000:3000
    environment:
      - TZ
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
    # Benutzer definierte Verbraucher
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```

### Dein vollständiges `.env`

```env
INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
INFLUX_SENSOR_WALLBOX_POWER=
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_INVERTER_POWER_FORECAST=Forecast:watt
INFLUX_SENSOR_HEATPUMP_POWER=
# Benutzer definierte Verbraucher
INFLUX_SENSOR_CUSTOM_POWER_01=AUFZUG:power
INFLUX_SENSOR_CUSTOM_POWER_02=THERME:power

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
# INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER,WALLBOX_POWER
```
