### ISSUE TITLE
Unrealistische Summenbildung bei lückenhaften Messreihen

### ISSUE THREAD

**Issue by q2doc** [solectrus/solectrus#3791]
### Beschreibung (auf Deutsch oder Englisch)

Bei der aktuellen Beta is bei mir ein einzelner Verbraucher größer als der Hausverbrauch:

![image](https://github.com/user-attachments/assets/cc844768-c2ee-4064-9f73-93447787a9e3)

Die Daten kommen per MQTT aus dem ioBroker, da der Shellie trotz "...#...." nicht direkt gefunden wird.

### Welche Version von SOLECTRUS verwendest du?

custom-consumers-129-g046c221a

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Raspberry Pi5 docker

### Dein vollständiges `docker-compose.yml` oder `compose.yml`

```yaml
services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:pr-3747 #next
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - postgresql
      - influxdb
      - redis
    ports:
      - '3000:3000'
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_CAR_BATTERY_SOC #Auto Ladestand
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED #Auto angeschlossen?
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  
  influxdb:
    image: influxdb:2.7-alpine #2.6-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    # Optional: Allow InfluxDB to be accessed from the outside.
    ports:
      - 8086:8086
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  
  postgresql:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  
  redis:
    image: redis:7-alpine
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus

  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest #pr-137
    environment:
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - MAPPING_0_TOPIC
      - MAPPING_0_MEASUREMENT
      - MAPPING_0_FIELD
      - MAPPING_0_TYPE
      - MAPPING_1_TOPIC
      - MAPPING_1_MEASUREMENT
      - MAPPING_1_FIELD
      - MAPPING_1_TYPE
      - MAPPING_2_TOPIC
      - MAPPING_2_MEASUREMENT_POSITIVE
      - MAPPING_2_MEASUREMENT_NEGATIVE
      - MAPPING_2_FIELD_POSITIVE
      - MAPPING_2_FIELD_NEGATIVE
      - MAPPING_2_TYPE
      - MAPPING_3_TOPIC
      - MAPPING_3_MEASUREMENT_POSITIVE
      - MAPPING_3_MEASUREMENT_NEGATIVE
      - MAPPING_3_FIELD_POSITIVE
      - MAPPING_3_FIELD_NEGATIVE
      - MAPPING_3_TYPE
      - MAPPING_4_TOPIC
      - MAPPING_4_MEASUREMENT
      - MAPPING_4_FIELD
      - MAPPING_4_TYPE
      - MAPPING_5_TOPIC
      - MAPPING_5_MEASUREMENT
      - MAPPING_5_FIELD
      - MAPPING_5_TYPE
      - MAPPING_6_TOPIC
      - MAPPING_6_MEASUREMENT
      - MAPPING_6_FIELD
      - MAPPING_6_TYPE
      - MAPPING_7_TOPIC
      - MAPPING_7_MEASUREMENT
      - MAPPING_7_FIELD
      - MAPPING_7_TYPE
      - MAPPING_8_TOPIC
      - MAPPING_8_MEASUREMENT
      - MAPPING_8_FIELD
      - MAPPING_8_TYPE
      - MAPPING_9_TOPIC
      - MAPPING_9_MEASUREMENT
      - MAPPING_9_FIELD
      - MAPPING_9_TYPE
      - MAPPING_10_TOPIC
      - MAPPING_10_MEASUREMENT
      - MAPPING_10_FIELD
      - MAPPING_10_TYPE
      - MAPPING_11_TOPIC
      - MAPPING_11_MEASUREMENT
      - MAPPING_11_FIELD
      - MAPPING_11_TYPE  
      - MAPPING_12_TOPIC
      - MAPPING_12_MEASUREMENT
      - MAPPING_12_FIELD
      - MAPPING_12_TYPE    
      - MAPPING_13_TOPIC
      - MAPPING_13_MEASUREMENT
      - MAPPING_13_FIELD
      - MAPPING_13_TYPE
      - MAPPING_14_TOPIC
      - MAPPING_14_MEASUREMENT
      - MAPPING_14_FIELD
      - MAPPING_14_TYPE
      - MAPPING_15_TOPIC
      - MAPPING_15_MEASUREMENT
      - MAPPING_15_FIELD
      - MAPPING_15_TYPE
      - MAPPING_16_TOPIC
      - MAPPING_16_MEASUREMENT
      - MAPPING_16_FIELD
      - MAPPING_16_TYPE
      - MAPPING_17_TOPIC
      - MAPPING_17_MEASUREMENT
      - MAPPING_17_FIELD
      - MAPPING_17_TYPE
      - MAPPING_18_TOPIC
      - MAPPING_18_MEASUREMENT
      - MAPPING_18_FIELD
      - MAPPING_18_TYPE
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
      
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest #develop
    environment:
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_CONFIGURATIONS
      - FORECAST_0_LATITUDE
      - FORECAST_0_LONGITUDE
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_0_DAMPING_MORNING
      - FORECAST_0_DAMPING_EVENING
      - FORECAST_1_LATITUDE
      - FORECAST_1_LONGITUDE
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_1_DAMPING_MORNING
      - FORECAST_1_DAMPING_EVENING
      - FORECAST_2_LATITUDE
      - FORECAST_2_LONGITUDE
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_2_DAMPING_MORNING
      - FORECAST_2_DAMPING_EVENING
      - FORECAST_3_LATITUDE
      - FORECAST_3_LONGITUDE
      - FORECAST_3_DECLINATION
      - FORECAST_3_AZIMUTH
      - FORECAST_3_KWP
      - FORECAST_3_DAMPING_MORNING
      - FORECAST_3_DAMPING_EVENING
      - FORECAST_INTERVAL
      - FORECAST_SOLAR_APIKEY
      - INFLUX_HOST
      - INFLUX_PORT
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${FORECAST_INFLUX_MEASUREMENT} #achtung ist anders!!!
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
      
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: '--scope solectrus --cleanup'
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus

## ab hier power splitter und neu:      
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:develop
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
    environment:
      - TZ
      - POWER_SPLITTER_INTERVAL=300
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_PORT
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL=redis://redis:6379/1
    links:
      - influxdb
      - redis
    depends_on:
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
```

### Dein vollständiges `.env`

```text
##################################################################
###                   Dashboard application                    ###
##################################################################

# Domain name or IP address of your host
APP_HOST= xxx

# Date of commissioning of your photovoltaic system
INSTALLATION_DATE= xxx

# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD= xxx

# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false

# Secret token to secure cookies, 128 chars long hexadecimal encoded string
SECRET_KEY_BASE= xxx
#
# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0

# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com

# Password for the PostgreSQL database, used by the app to comunicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to connect to the database!
POSTGRES_PASSWORD= xxx

##################################################################
###                      Sensor mapping                        ###
##################################################################

# Where to find the data in the InfluxDB
# Each sensor must be mapped to a measurement and a field
# The format is: INFLUX_SENSOR_NAME=MEASUREMENT:FIELD
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power

INFLUX_SENSOR_INVERTER_POWER=my-pv-measurement:inverter_power #pv:inverter_power
INFLUX_SENSOR_HOUSE_POWER=my-pv-measurement:house_power #pv:house_power   # notwendig für power splitter!
INFLUX_SENSOR_GRID_IMPORT_POWER=my-pv-measurement:grid_power_plus #pv:grid_import_power   # notwendig für power splitter!
INFLUX_SENSOR_GRID_EXPORT_POWER=my-pv-measurement:grid_power_minus #pv:grid_export_power
INFLUX_SENSOR_BATTERY_CHARGING_POWER=my-pv-measurement:bat_power_plus #pv:battery_charging_power
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=my-pv-measurement:bat_power_minus #pv:battery_discharging_power
INFLUX_SENSOR_BATTERY_SOC=my-pv-measurement:bat_fuel_charge #pv:battery_soc
INFLUX_SENSOR_WALLBOX_POWER=my-pv-measurement:wallbox_charge_power #pv:wallbox_power   # notwendig für power splitter!
INFLUX_SENSOR_CASE_TEMP=my-pv-measurement:WW-Temp #pv:case_temp alt war case_temp für Batterie
INFLUX_SENSOR_SYSTEM_STATUS=my-pv-measurement:system_status #pv:system_status
INFLUX_SENSOR_SYSTEM_STATUS_OK=my-pv-measurement:system_status_ok #pv:system_status_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=my-pv-measurement:grid_export_limit #pv:grid_export_limit
INFLUX_SENSOR_INVERTER_POWER_FORECAST=Forecast:watt #forecast:watt
INFLUX_SENSOR_HEATPUMP_POWER=my-pv-measurement:heatpump_power #heatpump:power   # notwendig für power splitter!
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power
INFLUX_SENSOR_CAR_BATTERY_SOC=Car:SOC1
INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=Car:ev1_connected

INFLUX_SENSOR_CUSTOM_POWER_01=Washer:power
INFLUX_SENSOR_CUSTOM_POWER_02=Dryer:power
INFLUX_SENSOR_CUSTOM_POWER_03=Dishwasher:power
INFLUX_SENSOR_CUSTOM_POWER_04=Herd:power
INFLUX_SENSOR_CUSTOM_POWER_05=Backofen:power
INFLUX_SENSOR_CUSTOM_POWER_06=Mikrowelle:power
INFLUX_SENSOR_CUSTOM_POWER_07=Kaffeemaschiene:power
INFLUX_SENSOR_CUSTOM_POWER_08=Klimaanlage:power

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER #,WALLBOX_POWER

##################################################################
###                       MQTT Collector                       ###
##################################################################

##### MQTT Broker credentials
MQTT_HOST= xxx
MQTT_PORT= xxx
MQTT_SSL=false
MQTT_USERNAME= xxx
MQTT_PASSWORD= xxx

##### Mappings

# Index of the mappings, starting with 0
# Example:
#
# MAPPING_0_TOPIC=example-device/0/ENERGY/INVERTER_POWER
# MAPPING_0_MEASUREMENT=EXAMPLE
# MAPPING_0_FIELD=inverter_power
# MAPPING_0_TYPE=integer # One of integer, float, string, boolean
#
# MAPPING_1_TOPIC=example-device/0/ENERGY/BAT_CHARGE_POWER
# MAPPING_1_MEASUREMENT=EXAMPLE
# MAPPING_1_FIELD=battery_charging_power
# MAPPING_1_TYPE=float
#

# PV Erzeugung
MAPPING_0_TOPIC=evcc/site/pv/1/power
MAPPING_0_MEASUREMENT=my-pv-measurement #pv
MAPPING_0_FIELD=inverter_power
MAPPING_0_TYPE=integer

# Hausverbrauch -->
MAPPING_1_TOPIC=evcc/site/homePower
MAPPING_1_MEASUREMENT=my-pv-measurement #pv
MAPPING_1_FIELD=house_power
MAPPING_1_TYPE=integer

# Netzbezug -->
MAPPING_2_TOPIC=evcc/site/gridPower #???warum auf evcc???
MAPPING_2_MEASUREMENT_POSITIVE=my-pv-measurement #pv
MAPPING_2_MEASUREMENT_NEGATIVE=my-pv-measurement #pv
MAPPING_2_FIELD_POSITIVE=grid_power_plus #grid_import_power
MAPPING_2_FIELD_NEGATIVE=grid_power_minus #grid_export_power
MAPPING_2_TYPE=integer

# Batterie Ladung/Bezug -->
MAPPING_3_TOPIC=evcc/site/battery/1/power #???warum auf evcc???
MAPPING_3_MEASUREMENT_POSITIVE=my-pv-measurement #pv
MAPPING_3_MEASUREMENT_NEGATIVE=my-pv-measurement #pv
MAPPING_3_FIELD_POSITIVE=bat_power_minus #battery_discharging_power
MAPPING_3_FIELD_NEGATIVE=bat_power_plus #battery_charging_power
MAPPING_3_TYPE=integer

# Batterie Ladung in % -->
MAPPING_4_TOPIC=evcc/site/battery/1/soc #???warum auf evcc???
MAPPING_4_MEASUREMENT=my-pv-measurement #pv
MAPPING_4_FIELD=bat_fuel_charge #battery_soc
MAPPING_4_TYPE=float

# Wallbox
#Summe der Wallboxen 1 & 2 zB =evcc/loadpoints/2/chargePower
MAPPING_5_TOPIC=javascript/0/solarflow/chargePowerSum
MAPPING_5_MEASUREMENT=my-pv-measurement #pv
MAPPING_5_FIELD=wallbox_charge_power #wallbox_power
MAPPING_5_TYPE=integer

# Wärmepumpe
MAPPING_6_TOPIC=javascript/0/Wärmepumpe/Inverter_Verbrauch
MAPPING_6_MEASUREMENT=my-pv-measurement #heatpump
MAPPING_6_FIELD=heatpump_power #power
MAPPING_6_TYPE=integer

# Batterie oder irgendweine Temperatur... geändert auf Warmwasser vorher Batterie: bydhvs/0/State/TempBatt #stiebel-isg/0/Info/ANLAGE/WARMWASSER/ISTTEMPERATUR
MAPPING_7_TOPIC=modbus/4/inputRegisters/30522_WW-Ist
MAPPING_7_MEASUREMENT=my-pv-measurement
MAPPING_7_FIELD=WW-Temp
MAPPING_7_TYPE=float


MAPPING_8_TOPIC=bydhvs/0/System/ErrorStr #evcc/site/batteryMode
MAPPING_8_MEASUREMENT=my-pv-measurement
MAPPING_8_FIELD=system_status
MAPPING_8_TYPE=string

# Soc Audi
MAPPING_9_TOPIC= xxx/status/batteryStatus/currentSOC_pct
MAPPING_9_MEASUREMENT=Car
MAPPING_9_FIELD=SOC1
MAPPING_9_TYPE=float

# Connect Audi ev1_connected
MAPPING_10_TOPIC=javascript/0/Auto_data/Ladestatus
MAPPING_10_MEASUREMENT=Car
MAPPING_10_FIELD=ev1_connected
MAPPING_10_TYPE=string

#Waschmaschiene
MAPPING_11_TOPIC=0_userdata/0/Solectrus/Custom-01
MAPPING_11_MEASUREMENT=Washer
MAPPING_11_FIELD=power
MAPPING_11_TYPE=float

#Trockner
MAPPING_12_TOPIC=0_userdata/0/Solectrus/Custom-02
MAPPING_12_MEASUREMENT=Dryer
MAPPING_12_FIELD=power
MAPPING_12_TYPE=float

#Spülmaschiene
MAPPING_13_TOPIC=0_userdata/0/Solectrus/Custom-03 #javascript/0/TestZahl #"shelly/0/shellyplus1pm#d4d4da08c8d0#1/Relay0/Power"
MAPPING_13_MEASUREMENT=Dishwasher
MAPPING_13_FIELD=power
MAPPING_13_TYPE=float

#Herd
MAPPING_14_TOPIC=0_userdata/0/Solectrus/Custom-04
MAPPING_14_MEASUREMENT=Herd
MAPPING_14_FIELD=power
MAPPING_14_TYPE=float

#Backofen
MAPPING_15_TOPIC=0_userdata/0/Solectrus/Custom-05
MAPPING_15_MEASUREMENT=Backofen
MAPPING_15_FIELD=power
MAPPING_15_TYPE=float

#Mikrowelle
MAPPING_16_TOPIC=0_userdata/0/Solectrus/Custom-06
MAPPING_16_MEASUREMENT=Mikrowelle
MAPPING_16_FIELD=power
MAPPING_16_TYPE=float

#Kaffeemaschiene
MAPPING_17_TOPIC=0_userdata/0/Solectrus/Custom-07
MAPPING_17_MEASUREMENT=Kaffeemaschiene
MAPPING_17_FIELD=power
MAPPING_17_TYPE=float

#Klimaanlage
MAPPING_18_TOPIC=0_userdata/0/Solectrus/Custom-08
MAPPING_18_MEASUREMENT=Klimaanlage
MAPPING_18_FIELD=power
MAPPING_18_TYPE=float

##################################################################
###                     Forecast collector                     ###
##################################################################

# API docs: https://doc.forecast.solar/doku.php?id=api:estimate

# Latitude of the plant location
FORECAST_LATITUDE= xxx

# Longitude of the plant location
FORECAST_LONGITUDE= xxx

# Plane declination: 0 (horizontal) - 90 (vertical)
# FORECAST_DECLINATION=30

# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
# FORECAST_AZIMUTH=20

# Installed modules power in kilowatt peak (kWp)
# FORECAST_KWP=8.4

# Optional damping factors (http://doc.forecast.solar/damping)
# FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional configuration for multiple planes
#
# Number of planes
FORECAST_CONFIGURATIONS=3
#
# Starting from 0, add params different from the values defined above
FORECAST_0_DECLINATION=36
FORECAST_0_AZIMUTH=-7
FORECAST_0_KWP=7.2
FORECAST_0_DAMPING_MORNING=0
FORECAST_0_DAMPING_EVENING=0.5
#
FORECAST_1_DECLINATION=10
FORECAST_1_AZIMUTH=83
FORECAST_1_KWP=1.2
FORECAST_1_DAMPING_MORNING=0
FORECAST_1_DAMPING_EVENING=0.6
#
FORECAST_2_DECLINATION=10
FORECAST_2_AZIMUTH=-97
FORECAST_2_KWP=1.2
ORECAST_2_DAMPING_MORNING=0.1
FORECAST_2_DAMPING_EVENING=0.5
#
# FORECAST_3_DECLINATION=50
# FORECAST_3_AZIMUTH=90
# FORECAST_3_KWP=2.58
#
# Available params are:
# - FORECAST_x_LATITUDE
# - FORECAST_x_LONGITUDE
# - FORECAST_x_DECLINATION
# - FORECAST_x_AZIMUTH
# - FORECAST_x_KWP
# - FORECAST_x_DAMPING_MORNING
# - FORECAST_x_DAMPING_EVENING

# Update interval in seconds, 900s = 15 minutes, the public (and free) API allows a minimum of 900 seconds
# BEWARE: Each plane counts as one request, so if you have multiple planes, you need to multiply the interval!
FORECAST_INTERVAL=1200

# Optional API key for registered users of forecast.solar (https://doc.forecast.solar/account_models)
FORECAST_SOLAR_APIKEY= xxx

# Measurement name for InfluxDB
FORECAST_INFLUX_MEASUREMENT=Forecast #forecast

##################################################################
###                 InfluxDB time series database              ###
##################################################################

# InfluxDB host
INFLUX_HOST=influxdb

# InfluxDB schema (http or https)
INFLUX_SCHEMA=http

# InfluxDB port
INFLUX_PORT= xxx

# Credentials for the InfluxDB, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME= xxx
INFLUX_PASSWORD= xxx
INFLUX_ADMIN_TOKEN= xxx

# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=my-solectrus-bucket

# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE= xxx
INFLUX_TOKEN_READ= xxx

# Volume path for storing the InfluxDB data
INFLUX_VOLUME_PATH=xxx/solectrus/influxdb

##################################################################
###                    PostgreSQL database                     ###
##################################################################

# Volume path for storing the PostgreSQL data
DB_VOLUME_PATH=xxx/solectrus/postgresql

##################################################################
###                 Redis in-memory database                   ###
##################################################################

# Volume path for storing the database snapshot
REDIS_VOLUME_PATH=xxx/solectrus/redis
```
