### ISSUE TITLE
Beta-Test für Balkonkraftwerke: Historische Daten teilweise verschwunden

### ISSUE THREAD

**Issue by WolfImBusch** [solectrus/solectrus#4201]
### Beschreibung (auf Deutsch oder Englisch)

Hallo @ledermann 

Wie immer konnte ich nicht warten und habe die "pr-4195" installiert wie von Dir beschrieben (Szenario 2). Ich denke, ich habe das richtig gemacht - die Anzeige "aktuell" funktioniert und zeigt mir nun die PV Leistung getrennt für meine Ost- und Westseite an. 

Leider fehlen mir nun historische Daten - auch nach Zurücksetzen und Neuberechnung der Tageszusammenfassung .. :-( Diese sind
- Ansicht "Woche": Die Tage Mo und Di 
- Ansicht "Monat": Alle Tage dieses Monats außer heute
- Ansicht "Jahr": Alle bisherigen Monate Jan, Feb, März

Edit: Sorry - ich war unpräzise. Es betrifft **nicht** alle historischen Daten, sondern "Erzeugung" und "Eigenverbrauch". 

Hilfe!! :-)

Gerne stelle ich auch meine compose/.env zur Verfügung - aber ich vermute, das wird nicht das Problem sein ..

<img width="1082" alt="Image" src="https://github.com/user-attachments/assets/02d57df2-e812-49b2-9bc1-cc306323074d" />

<img width="1082" alt="Image" src="https://github.com/user-attachments/assets/460a0f96-527b-495b-afe4-8db44909b3f4" />

Ich danke Dir und viele Grüße!!!

Alex

### Welche Version von SOLECTRUS verwendest du?

pr-4195

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Synology DS220+ (Docker)

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text

```

### Dein vollständiges `docker-compose.yml` oder `compose.yml`

```
##################################################################
###                          Generic                           ###
##################################################################

TZ=Europe/Berlin

##################################################################
###                   Dashboard application                    ###
##################################################################

# Domain name or IP address of your host
APP_HOST=192.168.178.22

# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2024-06-20

# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=........

# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false

# Secret token to secure cookies, 128 chars long hexadecimal encoded string
SECRET_KEY_BASE=......

# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0

# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com

# Password for the PostgreSQL database, used by the app to communicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to connect to the database!
POSTGRES_PASSWORD=.......

##################################################################
###                      Sensor mapping                        ###
##################################################################

# Where to find the data in the InfluxDB
# Each sensor must be mapped to a measurement and a field
# The format is: INFLUX_SENSOR_NAME=MEASUREMENT:FIELD
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power

INFLUX_SENSOR_INVERTER_POWER=pv:inverter_power
INFLUX_SENSOR_INVERTER_POWER_1=pv:power_east
INFLUX_SENSOR_INVERTER_POWER_2=pv:power_west
INFLUX_SENSOR_INVERTER_POWER_3=
INFLUX_SENSOR_INVERTER_POWER_4=
INFLUX_SENSOR_INVERTER_POWER_5=
INFLUX_SENSOR_HOUSE_POWER=pv:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=pv:grid_import_power
INFLUX_SENSOR_GRID_EXPORT_POWER=pv:grid_export_power
INFLUX_SENSOR_BATTERY_CHARGING_POWER=pv:battery_charging_power
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=pv:battery_discharging_power
INFLUX_SENSOR_BATTERY_SOC=pv:battery_soc
INFLUX_SENSOR_CAR_BATTERY_SOC=pv:vehiclesoc
INFLUX_SENSOR_WALLBOX_POWER=pv:wallbox_power
INFLUX_SENSOR_CASE_TEMP=pv:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=batcontrol:bat_mode
#INFLUX_SENSOR_SYSTEM_STATUS=
INFLUX_SENSOR_SYSTEM_STATUS_OK=
INFLUX_SENSOR_GRID_EXPORT_LIMIT=
INFLUX_SENSOR_INVERTER_POWER_FORECAST=forecast:watt
INFLUX_SENSOR_HEATPUMP_POWER=
INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=pv:wallbox_car_connected
INFLUX_SENSOR_CUSTOM_POWER_01=gasheizung:power
INFLUX_SENSOR_CUSTOM_POWER_02=gefrierschrank:power

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
INFLUX_EXCLUDE_FROM_HOUSE_POWER=WALLBOX_POWER

##################################################################
###                       MQTT Collector                       ###
##################################################################

##### MQTT Broker credentials
MQTT_HOST=192.168.178.22
MQTT_PORT=1883
MQTT_SSL=false
MQTT_USERNAME=.......
MQTT_PASSWORD=.......

##### Mappings

# Index of the mappings, starting with 0
# Example:
#
# MAPPING_0_TOPIC=example-device/0/ENERGY/INVERTER_POWER
# MAPPING_0_MEASUREMENT=EXAMPLE
# MAPPING_0_FIELD=inverter_power
# MAPPING_0_TYPE=integer # One of integer, float, string, boolean
#
# MAPPING_1_TOPIC=example-device/0/ENERGY/BAT_CHARGE_POWER
# MAPPING_1_MEASUREMENT=EXAMPLE
# MAPPING_1_FIELD=battery_charging_power
# MAPPING_1_TYPE=float
#
# ...
MAPPING_0_TOPIC=homeassistant/sensor/solarnet_pv_leistung/state
MAPPING_0_MEASUREMENT=pv
MAPPING_0_FIELD=inverter_power
MAPPING_0_TYPE=integer
MAPPING_1_TOPIC=homeassistant/sensor/solarnet_leistung_verbrauch/state
MAPPING_1_MEASUREMENT=pv
MAPPING_1_FIELD=house_power
MAPPING_1_TYPE=integer
MAPPING_2_TOPIC=homeassistant/sensor/smart_meter_ts_65a_3_wirkleistung/state
MAPPING_2_MEASUREMENT_POSITIVE=pv
MAPPING_2_MEASUREMENT_NEGATIVE=pv
MAPPING_2_FIELD_POSITIVE=grid_import_power
MAPPING_2_FIELD_NEGATIVE=grid_export_power
MAPPING_2_TYPE=integer
MAPPING_3_TOPIC=homeassistant/sensor/solarnet_leistung_von_der_batterie/state
MAPPING_3_MEASUREMENT_POSITIVE=pv
MAPPING_3_MEASUREMENT_NEGATIVE=pv
MAPPING_3_FIELD_POSITIVE=battery_discharging_power
MAPPING_3_FIELD_NEGATIVE=battery_charging_power
MAPPING_3_TYPE=integer
MAPPING_4_TOPIC=homeassistant/sensor/byd_battery_box_premium_hv_ladezustand/state
MAPPING_4_MEASUREMENT=pv
MAPPING_4_FIELD=battery_soc
MAPPING_4_TYPE=float
MAPPING_5_TOPIC=evcc/loadpoints/1/chargePower
MAPPING_5_MEASUREMENT=pv
MAPPING_5_FIELD=wallbox_power
MAPPING_5_TYPE=integer
MAPPING_6_TOPIC=homeassistant/sensor/byd_battery_box_premium_hv_temperatur/state
MAPPING_6_MEASUREMENT=pv
MAPPING_6_FIELD=case_temp
MAPPING_6_TYPE=float
MAPPING_7_TOPIC=evcc/loadpoints/1/connected
MAPPING_7_MEASUREMENT=pv
MAPPING_7_FIELD=wallbox_car_connected
MAPPING_7_TYPE=boolean
MAPPING_8_TOPIC=homeassistant/sensor/state_of_charge/state
MAPPING_8_MEASUREMENT=pv
MAPPING_8_FIELD=vehiclesoc
MAPPING_8_TYPE=float
MAPPING_9_TOPIC=Gasheizung/status/switch:0
MAPPING_9_JSON_KEY=apower
MAPPING_9_MEASUREMENT=gasheizung
MAPPING_9_FIELD=power
MAPPING_9_TYPE=float
MAPPING_10_TOPIC=Gefrierschrank/status/switch:0
MAPPING_10_JSON_KEY=apower
MAPPING_10_MEASUREMENT=gefrierschrank
MAPPING_10_FIELD=power
MAPPING_10_TYPE=float
MAPPING_11_TOPIC=batcontrol/mode
MAPPING_11_FORMULA="IF({value} = 10, 'DISCHARGE ALLOWED', IF({value} = 0, 'AVOID DISCHARGE', IF({value} = -1, 'CHARGE FROM GRID', 'UNKNOWN MODE')))"
MAPPING_11_MEASUREMENT=batcontrol
MAPPING_11_FIELD=bat_mode
MAPPING_11_TYPE=string
MAPPING_12_TOPIC=homeassistant/sensor/power_photovoltaics_east/state
MAPPING_12_MEASUREMENT=pv
MAPPING_12_FIELD=power_east
MAPPING_12_TYPE=float
MAPPING_13_TOPIC=homeassistant/sensor/power_photovoltaics_west/state
MAPPING_13_MEASUREMENT=pv
MAPPING_13_FIELD=power_west
MAPPING_13_TYPE=float


##################################################################
###                     Forecast collector                     ###
##################################################################

FORECAST_PROVIDER=solcast

# Number of planes (if you have more than one). Default is 1. Forecast.solar allows up to 4 planes, Solcast up to 2.
FORECAST_CONFIGURATIONS=2

# Update interval in seconds
FORECAST_INTERVAL=17280

# Measurement name for InfluxDB
FORECAST_INFLUX_MEASUREMENT=forecast

### Details for forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate

# Latitude of the plant location
# FORECAST_LATITUDE=50.12345

# Longitude of the plant location
# FORECAST_LONGITUDE=6.12345

# Plane declination: 0 (horizontal) - 90 (vertical)
# FORECAST_DECLINATION=30

# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
# FORECAST_AZIMUTH=20

# Installed modules power in kilowatt peak (kWp)
# FORECAST_KWP=8.4

# Optional damping factors (http://doc.forecast.solar/damping)
# FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional configuration for multiple planes
#
# Starting from 0, add params different from the values defined above
# FORECAST_0_DECLINATION=35
# FORECAST_0_AZIMUTH=-180
# FORECAST_0_KWP=5.32
#
# FORECAST_1_DECLINATION=38
# FORECAST_1_AZIMUTH=-90
# FORECAST_1_KWP=5.32
#
# FORECAST_2_DECLINATION=50
# FORECAST_2_AZIMUTH=0
# FORECAST_2_KWP=7.84
#
# FORECAST_3_DECLINATION=50
# FORECAST_3_AZIMUTH=90
# FORECAST_3_KWP=2.58
#
# Available params are:
# - FORECAST_x_LATITUDE
# - FORECAST_x_LONGITUDE
# - FORECAST_x_DECLINATION
# - FORECAST_x_AZIMUTH
# - FORECAST_x_KWP
# - FORECAST_x_DAMPING_MORNING
# - FORECAST_x_DAMPING_EVENING

# Optional API key for registered users of forecast.solar (https://doc.forecast.solar/account_models)
# FORECAST_SOLAR_APIKEY=abc123

### Details for solcast.com

SOLCAST_APIKEY=C9-HE5NiPUxBJt-ND52PKhs_Fd2PYktM
SOLCAST_SITE=1111-2222-3333-4444

SOLCAST_0_SITE=.......
SOLCAST_1_SITE=.......

##################################################################
###                 InfluxDB time series database              ###
##################################################################

# InfluxDB host
INFLUX_HOST=influxdb

# InfluxDB schema (http or https)
INFLUX_SCHEMA=http

# InfluxDB port
INFLUX_PORT=8086

# Credentials for the InfluxDB, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=.......
INFLUX_ADMIN_TOKEN=.......

# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=solectrus

# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=.......
INFLUX_TOKEN_READ=.......

# Volume path for storing the InfluxDB data
INFLUX_VOLUME_PATH=/volume1/docker/solectrus/influxdb

##################################################################
###                    PostgreSQL database                     ###
##################################################################

# Volume path for storing the PostgreSQL data
DB_VOLUME_PATH=/volume1/docker/solectrus/postgresql

##################################################################
###                 Redis in-memory database                   ###
##################################################################

# Volume path for storing the database snapshot
REDIS_VOLUME_PATH=/volume1/docker/solectrus/redis

##################################################################
###                 Tibber                                     ###
##################################################################
TIBBER_TOKEN=.......
TIBBER_INTERVAL=3600
INFLUX_MEASUREMENT_PRICES=Tibber-Preise
```

### Dein vollständiges `.env`

```
services:
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:latest
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
    environment:
      - TZ
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_PORT
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER      
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL=redis://redis:6379/1
    links:
      - influxdb
      - redis
    depends_on:
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
  dashboard:
    image: ghcr.io/solectrus/solectrus:pr-4195
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - postgresql
      - influxdb
      - redis
    ports:
      - 3001:3000
    environment:
      - TZ
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_INVERTER_POWER_1
      - INFLUX_SENSOR_INVERTER_POWER_2
      - INFLUX_SENSOR_INVERTER_POWER_3
      - INFLUX_SENSOR_INVERTER_POWER_4
      - INFLUX_SENSOR_INVERTER_POWER_5
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_CAR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - TZ
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  postgresql:
    image: postgres:16-alpine
    environment:
      - TZ
      - POSTGRES_PASSWORD
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  redis:
    image: redis:7-alpine
    environment:
      - TZ
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest
    environment:
      - TZ
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - MAPPING_0_TOPIC
      - MAPPING_0_MEASUREMENT
      - MAPPING_0_FIELD
      - MAPPING_0_TYPE
      - MAPPING_1_TOPIC
      - MAPPING_1_MEASUREMENT
      - MAPPING_1_FIELD
      - MAPPING_1_TYPE
      - MAPPING_2_TOPIC
      - MAPPING_2_MEASUREMENT_POSITIVE
      - MAPPING_2_MEASUREMENT_NEGATIVE
      - MAPPING_2_FIELD_POSITIVE
      - MAPPING_2_FIELD_NEGATIVE
      - MAPPING_2_TYPE
      - MAPPING_3_TOPIC
      - MAPPING_3_MEASUREMENT_POSITIVE
      - MAPPING_3_MEASUREMENT_NEGATIVE
      - MAPPING_3_FIELD_POSITIVE
      - MAPPING_3_FIELD_NEGATIVE
      - MAPPING_3_TYPE
      - MAPPING_4_TOPIC
      - MAPPING_4_MEASUREMENT
      - MAPPING_4_FIELD
      - MAPPING_4_TYPE
      - MAPPING_5_TOPIC
      - MAPPING_5_MEASUREMENT
      - MAPPING_5_FIELD
      - MAPPING_5_TYPE
      - MAPPING_6_TOPIC
      - MAPPING_6_MEASUREMENT
      - MAPPING_6_FIELD
      - MAPPING_6_TYPE
      - MAPPING_7_TOPIC
      - MAPPING_7_MEASUREMENT
      - MAPPING_7_FIELD
      - MAPPING_7_TYPE
      - MAPPING_8_TOPIC
      - MAPPING_8_MEASUREMENT
      - MAPPING_8_FIELD
      - MAPPING_8_TYPE
      - MAPPING_9_TOPIC
      - MAPPING_9_JSON_KEY
      - MAPPING_9_MEASUREMENT
      - MAPPING_9_FIELD
      - MAPPING_9_TYPE
      - MAPPING_10_TOPIC
      - MAPPING_10_JSON_KEY
      - MAPPING_10_MEASUREMENT
      - MAPPING_10_FIELD
      - MAPPING_10_TYPE
      - MAPPING_11_TOPIC
      - MAPPING_11_FORMULA
      - MAPPING_11_MEASUREMENT
      - MAPPING_11_FIELD
      - MAPPING_11_TYPE 
      - MAPPING_12_TOPIC
      - MAPPING_12_FORMULA          
      - MAPPING_12_MEASUREMENT
      - MAPPING_12_FIELD
      - MAPPING_12_TYPE
      - MAPPING_13_TOPIC
      - MAPPING_13_FORMULA          
      - MAPPING_13_MEASUREMENT
      - MAPPING_13_FIELD
      - MAPPING_13_TYPE      
      
      
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    environment:
      - TZ
      - FORECAST_PROVIDER
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_CONFIGURATIONS
      - FORECAST_0_LATITUDE
      - FORECAST_0_LONGITUDE
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_0_DAMPING_MORNING
      - FORECAST_0_DAMPING_EVENING
      - FORECAST_1_LATITUDE
      - FORECAST_1_LONGITUDE
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_1_DAMPING_MORNING
      - FORECAST_1_DAMPING_EVENING
      - FORECAST_2_LATITUDE
      - FORECAST_2_LONGITUDE
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_2_DAMPING_MORNING
      - FORECAST_2_DAMPING_EVENING
      - FORECAST_3_LATITUDE
      - FORECAST_3_LONGITUDE
      - FORECAST_3_DECLINATION
      - FORECAST_3_AZIMUTH
      - FORECAST_3_KWP
      - FORECAST_3_DAMPING_MORNING
      - FORECAST_3_DAMPING_EVENING
      - FORECAST_INTERVAL
      - FORECAST_SOLAR_APIKEY
      - INFLUX_HOST
      - INFLUX_PORT
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${FORECAST_INFLUX_MEASUREMENT}
      - FORECAST_DAMPING_MORNING
      - FORECAST_DAMPING_EVENING
      - FORECAST_HORIZON
      - FORECAST_INVERTER
      - SOLCAST_APIKEY
      - SOLCAST_SITE
      - SOLCAST_0_SITE
      - SOLCAST_1_SITE
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope solectrus --cleanup
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  tibber-collector:
    image: ghcr.io/solectrus/tibber-collector:latest
    environment:
      - TZ
      - TIBBER_TOKEN
      - TIBBER_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_PRICES}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```
