### ISSUE TITLE
Beta-Test für Balkonkraftwerke und andere Erzeuger

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/solectrus#4202]
### Beschreibung (auf Deutsch oder Englisch)

Ich habe mich für Variante 2 erstmal entschieden. Nach der Installation habe ich einige Anzeigeprobleme (sh. screenshots) unter IOS 18.4
- desweiteren sind bei mir alle Teile der Erzeugung in der Ansicht gleich gross, obwohl sie alle 3 verschieden sind
- Anzeigereihenfolge : in der Grafik wird es genau umgekehrt zum Tooltip angezeigt. Heisst in der Grafik ist InverterPower3 oben und 1 unten. Tooltip dementsprechend umgekehrt.
- fehlende historische Daten. Bei mir fehlen leider alle vergangenen Erzeugerdaten (SensorWert für Gesamterzeugung ist nicht geändert worden)

env und yaml kann ich gern zur Verfügung stellen (obwohl die etwas verwirrend bei mir ist, da noch eine sehr alte Installation)

![Image](https://github.com/user-attachments/assets/16ea0423-810c-49ea-aa1f-a42551f96ada)
![Image](https://github.com/user-attachments/assets/30d0b1e3-f25d-4a58-bf6d-f34f0a507bc2)
![Image](https://github.com/user-attachments/assets/a7732606-99ec-4449-92a9-0878caecd3d9)
![Image](https://github.com/user-attachments/assets/dcef0508-05fa-43d3-af85-abbfa7ea25e0)
![Image](https://github.com/user-attachments/assets/e48d28ba-67cf-488a-9f30-24cc2be1fcdc)
![Image](https://github.com/user-attachments/assets/aa085999-422d-4d29-8b73-cc7a3a10e96d)
![Image](https://github.com/user-attachments/assets/94f46ab0-de91-4945-b97f-dd4a52658ab7)
![Image](https://github.com/user-attachments/assets/04cabd34-4362-47ac-b5ca-ddb4f10f4048)
![Image](https://github.com/user-attachments/assets/66f66c3e-2a8c-4643-b884-39f89da985c6)

### Welche Version von SOLECTRUS verwendest du?

pr-4195

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Raspberry 4 8gb

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text

```

### Dein vollständiges `docker-compose.yml` oder `compose.yml`

```yaml
services:
  app:
#    image: ghcr.io/solectrus/solectrus:latest
    image: ghcr.io/solectrus/solectrus:pr-4195
#    image: ghcr.io/solectrus/solectrus:pr-4151
#    image: ghcr.io/solectrus/solectrus:next
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      db:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - db
      - influxdb
      - redis
    ports:
      - 3000:3000
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - DB_HOST=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT_PV
      - INFLUX_MEASUREMENT_FORECAST
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_CAR_BATTERY_SOC=Tesla1:SOC
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=my_wallbox:ev_connected
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
#      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
#      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
#      - INFLUX_SENSOR_BALCONY_INVERTER_POWER
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_INVERTER_POWER_1
      - INFLUX_SENSOR_INVERTER_POWER_2
      - INFLUX_SENSOR_INVERTER_POWER_3
      - INFLUX_SENSOR_INVERTER_POWER_4
      - INFLUX_SENSOR_INVERTER_POWER_5
 #     - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - WEB_CONCURRENCY
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 3000 || exit 1']
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:develop
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
    environment:
      - TZ
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_PORT
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - INFLUX_SENSOR_CAR_BATTERY_SOC=Tesla1:SOC
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=my_wallbox:ev_connected
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
  #    - INFLUX_SENSOR_BALCONY_INVERTER_POWER
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_INVERTER_POWER_1
      - INFLUX_SENSOR_INVERTER_POWER_2
      - INFLUX_SENSOR_INVERTER_POWER_3
      - INFLUX_SENSOR_INVERTER_POWER_4
      - INFLUX_SENSOR_INVERTER_POWER_5
      - REDIS_URL=redis://redis:6379/1
    links:
      - influxdb
      - redis
    depends_on:
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
  
  influxdb:
    image: influxdb:2.7-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    # Optional: Allow InfluxDB to be accessed from the outside.
    ports:
      - 8086:8086
    restart: always
    healthcheck:
      test: ['CMD', 'influx', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  db:
    # Don't change major version if you have an existing database!
    # If you have started with an older major version (like 15), you need to migrate your database.
    # This is not worth the effort, so don't do it.
    image: postgres:16-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:7-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_PV}
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_TOPIC_HOUSE_POW
      - MQTT_TOPIC_GRID_POW
      - MQTT_TOPIC_BAT_CHARGE_CURRENT
      - MQTT_TOPIC_BAT_FUEL_CHARGE
      - MQTT_TOPIC_BAT_POWER
      - MQTT_TOPIC_BAT_VOLTAGE
      - MQTT_TOPIC_CASE_TEMP
      - MQTT_TOPIC_CURRENT_STATE
      - MQTT_TOPIC_MPP1_POWER
      - MQTT_TOPIC_MPP2_POWER
      - MQTT_TOPIC_MPP3_POWER
      - MQTT_TOPIC_INVERTER_POWER
      - MQTT_TOPIC_WALLBOX_CHARGE_POWER
      - MQTT_FLIP_BAT_POWER
      - MAPPING_0_TOPIC
      - MAPPING_0_FIELD
      - MAPPING_0_MEASUREMENT
      - MAPPING_0_TYPE
      - MAPPING_1_TOPIC
      - MAPPING_1_FIELD_POSITIVE
      - MAPPING_1_FIELD_NEGATIVE
      - MAPPING_1_MEASUREMENT_POSITIVE
      - MAPPING_1_MEASUREMENT_NEGATIVE
      - MAPPING_1_TYPE
      - MAPPING_10_TOPIC
      - MAPPING_10_FIELD
      - MAPPING_10_MEASUREMENT
      - MAPPING_10_TYPE
      - MAPPING_2_TOPIC
      - MAPPING_2_FIELD_POSITIVE
      - MAPPING_2_FIELD_NEGATIVE
      - MAPPING_2_MEASUREMENT_POSITIVE
      - MAPPING_2_MEASUREMENT_NEGATIVE
      - MAPPING_2_TYPE
      - MAPPING_3_TOPIC
      - MAPPING_3_FIELD
      - MAPPING_3_MEASUREMENT
      - MAPPING_3_TYPE
      - MAPPING_4_TOPIC
      - MAPPING_4_FIELD
      - MAPPING_4_MEASUREMENT
      - MAPPING_4_TYPE
      - MAPPING_5_TOPIC
      - MAPPING_5_FIELD
      - MAPPING_5_MEASUREMENT
      - MAPPING_5_TYPE
      - MAPPING_6_TOPIC
      - MAPPING_6_FIELD
      - MAPPING_6_MEASUREMENT
      - MAPPING_6_TYPE
      - MAPPING_7_TOPIC
      - MAPPING_7_FIELD
      - MAPPING_7_MEASUREMENT
      - MAPPING_7_TYPE
      - MAPPING_8_TOPIC
      - MAPPING_8_FIELD
      - MAPPING_8_MEASUREMENT
      - MAPPING_8_TYPE
      - MAPPING_9_TOPIC
      - MAPPING_9_FIELD
      - MAPPING_9_MEASUREMENT
      - MAPPING_9_TYPE
      - MAPPING_11_TOPIC
      - MAPPING_11_FIELD
      - MAPPING_11_MEASUREMENT
      - MAPPING_11_TYPE
      - MAPPING_12_TOPIC
      - MAPPING_12_FIELD
      - MAPPING_12_MEASUREMENT
      - MAPPING_12_TYPE
      - MAPPING_13_TOPIC
      - MAPPING_13_FIELD
      - MAPPING_13_MEASUREMENT
      - MAPPING_13_TYPE
      - MAPPING_14_TOPIC
      - MAPPING_14_FIELD
      - MAPPING_14_MEASUREMENT
      - MAPPING_14_TYPE
      - MAPPING_15_TOPIC
      - MAPPING_15_FIELD
      - MAPPING_15_MEASUREMENT
      - MAPPING_15_TYPE
      - MAPPING_16_TOPIC
      - MAPPING_16_FIELD
      - MAPPING_16_MEASUREMENT
      - MAPPING_16_TYPE
      - MAPPING_17_TOPIC
      - MAPPING_17_FIELD
      - MAPPING_17_MEASUREMENT
      - MAPPING_17_TYPE
      - MAPPING_18_TOPIC
      - MAPPING_18_FIELD
      - MAPPING_18_MEASUREMENT
      - MAPPING_18_TYPE
      - MAPPING_19_TOPIC
      - MAPPING_19_FIELD
      - MAPPING_19_MEASUREMENT
      - MAPPING_19_TYPE
      - MAPPING_20_TOPIC
      - MAPPING_20_FIELD
      - MAPPING_20_MEASUREMENT
      - MAPPING_20_TYPE
      - MAPPING_21_TOPIC
      - MAPPING_21_FIELD
      - MAPPING_21_MEASUREMENT
      - MAPPING_21_TYPE
      - MAPPING_22_TOPIC
      - MAPPING_22_FIELD
      - MAPPING_22_MEASUREMENT
      - MAPPING_22_TYPE
      - MAPPING_23_TOPIC
      - MAPPING_23_FIELD
      - MAPPING_23_MEASUREMENT
      - MAPPING_23_TYPE
      - MAPPING_24_TOPIC
      - MAPPING_24_FIELD
      - MAPPING_24_MEASUREMENT
      - MAPPING_24_TYPE
      - MAPPING_25_TOPIC
      - MAPPING_25_FIELD
      - MAPPING_25_MEASUREMENT
      - MAPPING_25_TYPE
      - MAPPING_26_TOPIC
      - MAPPING_26_FIELD
      - MAPPING_26_MEASUREMENT
      - MAPPING_26_TYPE
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'
```

### Dein vollständiges `.env`

```text
INFLUX_BUCKET=solectrus
INFLUX_MEASUREMENT_PV=my-pv-measurement
INFLUX_MEASUREMENT_FORECAST=Forecast
INFLUX_SENSOR_WALLBOX_POWER=my-pv-measurement:wallbox_charge_power
INFLUX_SENSOR_GRID_IMPORT_POWER=my-pv-measurement:grid_power_plus
INFLUX_SENSOR_HOUSE_POWER=my-pv-measurement:house_power
INFLUX_SENSOR_CAR_BATTERY_SOC=Tesla1:SOC
INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=my_wallbox:ev_connected
INFLUX_SENSOR_INVERTER_POWER_FORECAST=Forecast:watt
#INFLUX_SENSOR_BATTERY_CHARGING_POWER=my_pv_measurement:bat_power_minus
#INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=my_pv_measurement:bat_power_plus
INFLUX_SENSOR_CUSTOM_POWER_01=PS5pro:power
INFLUX_SENSOR_CUSTOM_POWER_02=BoschGS:power
INFLUX_SENSOR_CUSTOM_POWER_03=BoschWS:power
INFLUX_SENSOR_CUSTOM_POWER_04=BoschBO:power
INFLUX_SENSOR_CUSTOM_POWER_05=Haier:power
INFLUX_SENSOR_CUSTOM_POWER_06=Nebengeb:power
INFLUX_SENSOR_CUSTOM_POWER_07=Heizung:power
INFLUX_SENSOR_CUSTOM_POWER_08=Kueche:power
INFLUX_SENSOR_INVERTER_POWER=my-pv-measurement:inverter_power
INFLUX_SENSOR_INVERTER_POWER_1=my_pv_measurement:pvneben
INFLUX_SENSOR_INVERTER_POWER_2=my_pv_measurement:pvhaupt
INFLUX_SENSOR_INVERTER_POWER_3=my_pv_measurement:pvgarten
INFLUX_SENSOR_INVERTER_POWER_4=
INFLUX_SENSOR_INVERTER_POWER_5=
#INFLUX_SENSOR_BALCONY_INVERTER_POWER=balcony:inverter_power
#INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER, CUSTOM_POWER_07
#
# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
#
# Volume path for storing the Influx data
INFLUX_VOLUME_PATH=/home/pi/solectrus/influxdb
#
# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5
POWER_SPLITTER_INTERVAL=300
#SHELLY_HOST=192.168.178.115 
#SHELLY_INTERVAL=5
##################################################################
# REDIS settings
#
REDIS_VOLUME_PATH=/home/pi/solectrus/redis

##################################################################
# PostgreSQL database settings
#
DB_VOLUME_PATH=/home/pi/solectrus/postgresql

##################################################################
# MQTT Collector

# MQTT Broker credentials
MQTT_HOST=192.168.178.80
MQTT_PORT=1883
MQTT_SSL=false


# MQTT topics (this is only an example, change to your needs!)
# This example is for using https://github.com/nobl/ioBroker.senec (which in most cases is not necessary, because there is a SENEC collector)
#MQTT_TOPIC_HOUSE_POW=evcc/site/homePower
MAPPING_0_TOPIC=Solectrus/0 userdata/0/Hausverbrauch
MAPPING_0_FIELD=house_power
MAPPING_0_MEASUREMENT=my-pv-measurement
MAPPING_0_TYPE=integer
#MQTT_TOPIC_GRID_POW=evcc/site/gridPower
MAPPING_1_TOPIC=evcc/site/grid/power
MAPPING_1_FIELD_POSITIVE=grid_power_plus
MAPPING_1_FIELD_NEGATIVE=grid_power_minus
MAPPING_1_MEASUREMENT_POSITIVE=my-pv-measurement
MAPPING_1_MEASUREMENT_NEGATIVE=my-pv-measurement
MAPPING_1_TYPE=integer
MQTT_TOPIC_BAT_CHARGE_CURRENT=evcc/site/batteryPower
#MQTT_TOPIC_BAT_FUEL_CHARGE=evcc/site/batterySoc
MAPPING_10_TOPIC=evcc/site/batterySoc
MAPPING_10_FIELD=bat_fuel_charge
MAPPING_10_MEASUREMENT=my-pv-measurement
MAPPING_10_TYPE=float
#MQTT_TOPIC_BAT_POWER=evcc/site/batteryPower
MAPPING_2_TOPIC=evcc/site/batteryPower
MAPPING_2_FIELD_POSITIVE=bat_power_minus
MAPPING_2_FIELD_NEGATIVE=bat_power_plus
MAPPING_2_MEASUREMENT_POSITIVE=my-pv-measurement
MAPPING_2_MEASUREMENT_NEGATIVE=my-pv-measurement
MAPPING_2_TYPE=integer
MQTT_TOPIC_BAT_VOLTAGE=evcc/site/homePower
#MQTT_TOPIC_CASE_TEMP=Solectrus/bydhvs/0/State/TempBatt
MAPPING_3_TOPIC=Solectrus/bydhvs/0/State/TempBatt
MAPPING_3_FIELD=case_temp
MAPPING_3_MEASUREMENT=my-pv-measurement
MAPPING_3_TYPE=float
#MQTT_TOPIC_CURRENT_STATE=Solectrus/0 userdata/0/Solar/Status Wechselrichter/Status Wechselrichter
MAPPING_4_TOPIC=Solectrus/0 userdata/0/Solar/Status Wechselrichter/Status Wechselrichter
MAPPING_4_FIELD=current_state
MAPPING_4_MEASUREMENT=my-pv-measurement
MAPPING_4_TYPE=string
#MQTT_TOPIC_MPP1_POWER=evcc/site/pv/1/Power
MAPPING_5_TOPIC=evcc/site/pv/1/Power
MAPPING_5_FIELD=mpp1_power
MAPPING_5_MEASUREMENT=my-pv-measurement
MAPPING_5_TYPE=integer
#MQTT_TOPIC_MPP2_POWER=evcc/site/pv/2/Power
MAPPING_6_TOPIC=evcc/site/pv/2/Power
MAPPING_6_FIELD=mpp2_power
MAPPING_6_MEASUREMENT=my-pv-measurement
MAPPING_6_TYPE=integer
#MQTT_TOPIC_MPP3_POWER=evcc/site/pv/3/Power
MAPPING_7_TOPIC=evcc/site/pv/3/Power
MAPPING_7_FIELD=mpp3_power
MAPPING_7_MEASUREMENT=my-pv-measurement
MAPPING_7_TYPE=integer
#MQTT_TOPIC_INVERTER_POWER=Solectrus/PVohneBKW
MAPPING_8_TOPIC=evcc/site/pvPower
MAPPING_8_FIELD=inverter_power
MAPPING_8_MEASUREMENT=my-pv-measurement
MAPPING_8_TYPE=integer
#MQTT_TOPIC_WALLBOX_CHARGE_POWER=evcc/loadpoints/1/chargePower
MAPPING_9_TOPIC=evcc/loadpoints/1/chargePower
MAPPING_9_FIELD=wallbox_charge_power
MAPPING_9_MEASUREMENT=my-pv-measurement
MAPPING_9_TYPE=integer
MAPPING_11_TOPIC=Solectrus/0 userdata/0/TeslaSOC
MAPPING_11_FIELD=SOC
MAPPING_11_MEASUREMENT=Tesla1
MAPPING_11_TYPE=integer
MAPPING_12_TOPIC=Solectrus/mqtt/1/evcc/loadpoints/1/connected
MAPPING_12_FIELD=ev_connected
MAPPING_12_MEASUREMENT=my_wallbox
MAPPING_12_TYPE=boolean
MAPPING_13_TOPIC=Solectrus/PS5pro
MAPPING_13_FIELD=power
MAPPING_13_MEASUREMENT=PS5pro
MAPPING_13_TYPE=integer
MAPPING_14_TOPIC=Solectrus/BoschGS
MAPPING_14_FIELD=power
MAPPING_14_MEASUREMENT=BoschGS
MAPPING_14_TYPE=integer
MAPPING_15_TOPIC=Solectrus/BoschWS
MAPPING_15_FIELD=power
MAPPING_15_MEASUREMENT=BoschWS
MAPPING_15_TYPE=integer
MAPPING_16_TOPIC=Solectrus/BoschBO
MAPPING_16_FIELD=power
MAPPING_16_MEASUREMENT=BoschBO
MAPPING_16_TYPE=integer
MAPPING_17_TOPIC=Solectrus/Haier
MAPPING_17_FIELD=power
MAPPING_17_MEASUREMENT=Haier
MAPPING_17_TYPE=integer
MAPPING_18_TOPIC=Solectrus/Nebengeb
MAPPING_18_FIELD=power
MAPPING_18_MEASUREMENT=Nebengeb
MAPPING_18_TYPE=integer
MAPPING_19_TOPIC=evcc/loadpoints/3/chargePower
MAPPING_19_FIELD=power
MAPPING_19_MEASUREMENT=Heizung
MAPPING_19_TYPE=integer
MAPPING_20_TOPIC=Solectrus/Kueche
MAPPING_20_FIELD=power
MAPPING_20_MEASUREMENT=Kueche
MAPPING_20_TYPE=integer
MAPPING_21_TOPIC=Solectrus/mqtt/1/evcc/site/pv/3/power
MAPPING_21_FIELD=inverter_power
MAPPING_21_MEASUREMENT=balcony
MAPPING_21_TYPE=integer
MAPPING_22_TOPIC=evcc/site/pv/2/power
MAPPING_22_FIELD=pvhaupt
MAPPING_22_MEASUREMENT=my_pv_measurement
MAPPING_22_TYPE=integer
MAPPING_23_TOPIC=evcc/site/pv/1/power
MAPPING_23_FIELD=pvneben
MAPPING_23_MEASUREMENT=my_pv_measurement
MAPPING_23_TYPE=integer
MAPPING_24_TOPIC=evcc/site/pv/3/power
MAPPING_24_FIELD=pvgarten
MAPPING_24_MEASUREMENT=my_pv_measurement
MAPPING_24_TYPE=integer
#MAPPING_25_TOPIC=evcc/site/pv/3/power
#MAPPING_25_FIELD=pvgarten
#MAPPING_25_MEASUREMENT=my_pv_measurement
#MAPPING_25_TYPE=integer
```
