### ISSUE TITLE
Mehrere Shelly abfragen

### ISSUE THREAD

**Issue by hj-hefer** [solectrus/solectrus#4293]
Bekomme sobald ich mehr als 2 Shelly abfragen möchte fehlermeldungen im docker-composer up -d

folgende Werte im compose.ymal:

```yaml
services:
  shelly-collector-Fahrrad:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST=${SHELLY_HOST_Fahrrad}
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY_Fahrrad}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  shelly-collector-Waschmaschine:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST=${SHELLY_HOST_Waschmaschine}
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY_Waschmaschine}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
shelly-collector-Backofen:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST=${SHELLY_HOST_Backofen}
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY_Backofen}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
shelly-collector-Kuehlschrank:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST=${SHELLY_HOST_Kuehlschrank}
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY_Kuehlschrank}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
shelly-collector-Spuelmaschine:
    image: ghcr.io/solectrus/shelly-collector:latest
    environment:
      - TZ
      - SHELLY_HOST=${SHELLY_HOST_Spuelmaschine}
      - SHELLY_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SHELLY_Spuelmaschine}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  dashboard:
...
```

und folgendes im .env

```env
SHELLY_HOST_Fahrrad=192.168.11.101
SHELLY_HOST_Waschmaschine=192.168.11.104
SHELLY_HOST_Spuelmaschine=192.168.11.105
SHELLY_HOST_Backofen=192.168.11.108
SHELLY_HOST_Kuehlschrank=192.168.11.109
SHELLY_INTERVAL=5
INFLUX_MEASUREMENT_SHELLY_Fahrrad=Fahrrad
INFLUX_MEASUREMENT_SHELLY_Waschmaschine=Waschmaschine
INFLUX_MEASUREMENT_SHELLY_Spuelmaschine=Spuelmaschine
INFLUX_MEASUREMENT_SHELLY_Backofen=Backofen
INFLUX_MEASUREMENT_SHELLY_Kuehlschrank=Kuelschrank
....
INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
INFLUX_SENSOR_WALLBOX_POWER=pv:wallbox_power
INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=pv:car_connected
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_INVERTER_POWER_FORECAST=forecast:watt
INFLUX_SENSOR_HEATPUMP_POWER=
INFLUX_SENSOR_CAR_BATTERY_SOC=car:battery_soc
INFLUX_SENSOR_CUSTOM_POWER_01=Fahrrad:power
INFLUX_SENSOR_CUSTOM_POWER_02=Waschmaschine:power
INFLUX_SENSOR_CUSTOM_POWER_03=Backofen:power
INFLUX_SENSOR_CUSTOM_POWER_04=Spuelmaschine:power
INFLUX_SENSOR_CUSTOM_POWER_05=Kuehlschrank:power
```
