### ISSUE TITLE
Problem Verbindung zu postgresql nach Update

### ISSUE THREAD

**Issue by fugazzy** [solectrus/solectrus#4381]
### Beschreibung (auf Deutsch oder Englisch)

Hallo, ich habe meine Installation upgedated. Leider war der Festplattenspeicher zu knapp geworden, sodass es beim herunterladen der neuen Images zu Problemen gekommen ist.
Nach dem Freiräumen habe ich es erneut probiert und es schien auch geklappt zu haben. Alle Container laufen. Nur die Verbindung aus dem Container "App" zur postgresql funktioniert nicht mehr: 
nc: db (172.18.0.7:5432): Host is unreachable
Waiting for PostgreSQL on db:5432 ..
Die Container laufen in Portainer. IP-Adresse des Container scheint zu stimmen.
In den Logs des Containers "DB" finde ich keine Auffälligkeiten.

### Welche Version von SOLECTRUS verwendest du?

0.19.1

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Portainer

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text
nc: db (172.18.0.7:5432): Host is unreachable
Waiting for PostgreSQL on db:5432 ..
```

### Dein vollständiges `docker-compose.yml` oder `compose.yml`

```yaml
Logo
Home
Solectrus

Dashboard

Templates

Stacks
Containers
Images
Networks
Volumes
Events

Host

Administration

User-related


Environment-related

Registries
Licenses

Logs

Notifications

Settings

©
Portainer Business Edition
2.27.6 LTS
Containers>root-app-1>Inspect
Container inspect


admin
Inspect
{
    "AppArmorProfile": "",
    "Args": [
        "./bin/rails",
        "server"
    ],
    "Config": {
        "AttachStderr": true,
        "AttachStdin": false,
        "AttachStdout": true,
        "Cmd": [
            "./bin/rails",
            "server"
        ],
        "Domainname": "",
        "Entrypoint": [
            "docker/entrypoint.sh"
        ],
        "Env": [
            "INFLUX_ORG=xxx",
            "DB_PASSWORD=xxx",
            "FRAME_ANCESTORS",
            "INFLUX_MEASUREMENT_FORECAST=Forecast",
            "REDIS_URL=redis://redis:6379/1",
            "INFLUX_BUCKET=solectrus",
            "SECRET_KEY_BASE=xxx",
            "ADMIN_PASSWORD=xxx",
            "WEB_CONCURRENCY=0",
            "DB_USER=postgres",
            "FORCE_SSL=false",
            "INFLUX_MEASUREMENT_PV",
            "APP_HOST=192.168.10.20",
            "INSTALLATION_DATE=2023-05-16",
            "DB_HOST=db",
            "INFLUX_TOKEN=xxx",
            "INFLUX_HOST=xxx",
            "INFLUX_POLL_INTERVAL",
            "PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "RUBY_VERSION=3.4.3",
            "RUBY_DOWNLOAD_URL=https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.3.tar.xz",
            "RUBY_DOWNLOAD_SHA256=xxx",
            "GEM_HOME=/usr/local/bundle",
            "BUNDLE_SILENCE_ROOT_WARNING=1",
            "BUNDLE_APP_CONFIG=/usr/local/bundle",
            "RAILS_LOG_TO_STDOUT=true",
            "RAILS_SERVE_STATIC_FILES=true",
            "RAILS_ENV=production",
            "LD_PRELOAD=/usr/lib/libjemalloc.so.2",
            "COMMIT_SHA=xxx",
            "COMMIT_TIME=2025-04-22T15:26:27+02:00",
            "COMMIT_VERSION=v0.19.1",
            "COMMIT_BRANCH=v0.19.1"
        ],
        "ExposedPorts": {
            "3000/tcp": {}
        },
        "Healthcheck": {
            "Test": [
                "CMD-SHELL",
                "nc -z 127.0.0.1 3000 || exit 1"
            ]
        },
        "Hostname": "3df63577c6ca",
        "Image": "ghcr.io/solectrus/solectrus:latest",
        "Labels": {
            "com.centurylinklabs.watchtower.scope": "solectrus",
            "com.docker.compose.config-hash": "xxx",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.depends_on": "redis:service_healthy:false,db:service_healthy:false",
            "com.docker.compose.image": "sha256:xxx",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "root",
            "com.docker.compose.project.config_files": "/root/compose.yaml",
            "com.docker.compose.project.working_dir": "/root",
            "com.docker.compose.service": "app",
            "com.docker.compose.version": "2.32.4",
            "maintainer": "georg@ledermann.dev",
            "org.opencontainers.image.created": "2025-04-22T13:32:28.492Z",
            "org.opencontainers.image.description": "SOLECTRUS is a smart photovoltaic dashboard that displays your energy production and consumption. It also calculates costs and savings, helping you maximize the benefits of your solar system.",
            "org.opencontainers.image.licenses": "AGPL-3.0",
            "org.opencontainers.image.revision": "100117b3b9d230d43b62e80d463ddbf77edc6274",
            "org.opencontainers.image.source": "https://github.com/solectrus/solectrus",
            "org.opencontainers.image.title": "solectrus",
            "org.opencontainers.image.url": "https://github.com/solectrus/solectrus",
            "org.opencontainers.image.version": "0.19.1"
        },
        "MacAddress": "02:42:ac:12:00:07",
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "app",
        "Volumes": null,
        "WorkingDir": "/app"
    },
    "Created": "2025-06-03T18:42:35.373257296Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/ec78e5e8d97dabbd742f639623af3988b07ea30b4893696a6d40420fb6592162-init/diff:/var/lib/docker/overlay2/a0d45d68ef0f3e15c0637e93c81f2a8daf62bf2321d48069c35825050756342a/diff:/var/lib/docker/overlay2/338a7bcd39778d03550224ac1f637839bd4a3a05f2c0b144b44d5b97bcbc8905/diff:/var/lib/docker/overlay2/6fd9c57d7122c179281f343e20b94802380a6531f9fc8ec7ec081a9e2ef3088b/diff:/var/lib/docker/overlay2/3c980156361853d6a84fffa87b4a8444acf4c12aada4dfe1a87bb205bbd4ee84/diff:/var/lib/docker/overlay2/28203ea59867f4d16da3b8045340528f8b6ab185e522ca10b8c4914a01b53d61/diff:/var/lib/docker/overlay2/ef08ceb3e2189f7715c570379f6daa07729281181b745aaf5c52218a22c20f47/diff:/var/lib/docker/overlay2/013edfae5d3e150f6267b41cb8fb4b7ec01ce65894ff60c898db8501f320208a/diff:/var/lib/docker/overlay2/22e4c4be27b7de95afc1a814245f4c707603aee81e1a0b3b870415fc13f380ce/diff:/var/lib/docker/overlay2/cacbe926406199b0b9bbb41d2b767020c0249a8a8323429e69a7b65f83720e56/diff",
            "MergedDir": "/var/lib/docker/overlay2/ec78e5e8d97dabbd742f639623af3988b07ea30b4893696a6d40420fb6592162/merged",
            "UpperDir": "/var/lib/docker/overlay2/ec78e5e8d97dabbd742f639623af3988b07ea30b4893696a6d40420fb6592162/diff",
            "WorkDir": "/var/lib/docker/overlay2/ec78e5e8d97dabbd742f639623af3988b07ea30b4893696a6d40420fb6592162/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": null,
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "private",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": null,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "journald"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware",
            "/sys/devices/virtual/powercap"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "root_default",
        "OomKillDisable": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "3000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "3000"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/ee31b1b81c187dc75b19d1d0ea3b184a09168908f809f0e9980943fbbd21ff3d/hostname",
    "HostsPath": "/var/lib/docker/containers/ee31b1b81c187dc75b19d1d0ea3b184a09168908f809f0e9980943fbbd21ff3d/hosts",
    "Id": "ee31b1b81c187dc75b19d1d0ea3b184a09168908f809f0e9980943fbbd21ff3d",
    "Image": "sha256:592410c86f71f4b95d26ab96597fd49c4d63561259f461e1b8b3a3a06642fe10",
    "LogPath": "",
    "MountLabel": "",
    "Mounts": [],
    "Name": "/root-app-1",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "root_default": {
                "Aliases": [
                    "root-app-1",
                    "app",
                    "3df63577c6ca",
                    "ee31b1b81c18"
                ],
                "DNSNames": [
                    "root-app-1",
                    "app",
                    "3df63577c6ca",
                    "ee31b1b81c18"
                ],
                "DriverOpts": null,
                "EndpointID": "cf809c18b8c31a749958ef88b102db4351de9ae71dd6cf26eafad3b8fe4ba685",
                "Gateway": "172.18.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "172.18.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": [
                    "root-db-1:db",
                    "root-db-1:db-1",
                    "root-db-1:root-db-1",
                    "root-redis-1:redis",
                    "root-redis-1:redis-1",
                    "root-redis-1:root-redis-1"
                ],
                "MacAddress": "02:42:ac:12:00:07",
                "NetworkID": "1e0bd3f89698db93db96740d8f1c50d6933452dc307e591209c43ad3ab44163a"
            }
        },
        "Ports": {
            "3000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3000"
                },
                {
                    "HostIp": "::",
                    "HostPort": "3000"
                }
            ]
        },
        "SandboxID": "121a9de13868db5a011bce3134f3693449fb84992a10e088d51609713db904ae",
        "SandboxKey": "/var/run/docker/netns/121a9de13868",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "docker/entrypoint.sh",
    "Platform": "linux",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/ee31b1b81c187dc75b19d1d0ea3b184a09168908f809f0e9980943fbbd21ff3d/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2025-06-04T08:07:50.601293014Z",
        "Health": {
            "FailingStreak": 124,
            "Log": [
                {
                    "End": "2025-06-04T11:07:59.712357214+02:00",
                    "ExitCode": 1,
                    "Output": "",
                    "Start": "2025-06-04T11:07:59.640078913+02:00"
                },
                {
                    "End": "2025-06-04T11:08:29.782272418+02:00",
                    "ExitCode": 1,
                    "Output": "",
                    "Start": "2025-06-04T11:08:29.713617187+02:00"
                },
                {
                    "End": "2025-06-04T11:08:59.85068508+02:00",
                    "ExitCode": 1,
                    "Output": "",
                    "Start": "2025-06-04T11:08:59.784239623+02:00"
                },
                {
                    "End": "2025-06-04T11:09:29.917496958+02:00",
                    "ExitCode": 1,
                    "Output": "",
                    "Start": "2025-06-04T11:09:29.852563884+02:00"
                },
                {
                    "End": "2025-06-04T11:09:59.987088865+02:00",
                    "ExitCode": 1,
                    "Output": "",
                    "Start": "2025-06-04T11:09:59.918457343+02:00"
                }
            ],
            "Status": "unhealthy"
        },
        "OOMKilled": false,
        "Paused": false,
        "Pid": 1848807,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2025-06-04T08:07:50.827062158Z",
        "Status": "running"
    }
}
```

### Dein vollständiges `.env`

```text
Portainer?
```
