### ISSUE TITLE
Diagramm: Säulen für Akkubeladung fehlen

### ISSUE THREAD

**Issue by spirit0607** [solectrus/solectrus#4394]
### Beschreibung

In der Jahres- und Gesamtübersicht wird die Akku Beladung teilweise nicht angezeigt (siehe Bilder). In der Ansicht Monat- und Woche werden die Daten korrekt angezeigt.

<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/20fb9c5c-64db-4df3-95b8-1395b5c8f5b0" />
<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/794846e0-7c68-43d4-8d6a-976fba8897ca" />
<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/bf4a2713-1ae2-477c-b0d6-d40817d828a1" />
<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/651a65e8-77c9-4e62-9d64-47875f728372" />

### Welche Version von SOLECTRUS verwendest du?

0.20.0

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Synology NAS

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text

```

### Deine vollständige `docker-compose.yml` oder `compose.yml`

```yaml
version: "3.7"

services:
  app:
    image: ghcr.io/solectrus/solectrus:latest
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      - db
      - influxdb
      - redis
    links:
      - db
      - influxdb
      - redis
    ports:
      - 3000:3000
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - INSTALLATION_DATE
      - ELECTRICITY_PRICE
      - FEED_IN_TARIFF
      - ADMIN_PASSWORD
      - DB_HOST=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_CAR_BATTERY_SOC
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - FRAME_ANCESTORS
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
    restart: always

  influxdb:
    image: influxdb:2.7-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    ports:
      - 8086:8086
    restart: always
    healthcheck:
      test: ['CMD', 'influx', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: postgres:14-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s

  # senec-collector:
  #   image: ghcr.io/solectrus/senec-collector:latest
  #  depends_on:
  #    - influxdb
  #  links:
  #     - influxdb
  #  environment:
  #    - SENEC_HOST
  #    - SENEC_INTERVAL
  #    - INFLUX_HOST
  #    - INFLUX_SCHEMA
  #    - INFLUX_PORT
  #    - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
  #    - INFLUX_ORG
  #    - INFLUX_BUCKET
  #  restart: always

  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_SSL
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MAPPING_0_TOPIC
      - MAPPING_0_MEASUREMENT
      - MAPPING_0_FIELD
      - MAPPING_0_TYPE
      - MAPPING_1_TOPIC
      - MAPPING_1_MEASUREMENT
      - MAPPING_1_FIELD
      - MAPPING_1_TYPE
      - MAPPING_2_TOPIC
      - MAPPING_2_MEASUREMENT_POSITIVE
      - MAPPING_2_MEASUREMENT_NEGATIVE
      - MAPPING_2_FIELD_POSITIVE
      - MAPPING_2_FIELD_NEGATIVE
      - MAPPING_2_TYPE
      - MAPPING_3_TOPIC
      - MAPPING_3_MEASUREMENT_POSITIVE
      - MAPPING_3_MEASUREMENT_NEGATIVE
      - MAPPING_3_FIELD_POSITIVE
      - MAPPING_3_FIELD_NEGATIVE
      - MAPPING_3_TYPE
      - MAPPING_4_TOPIC
      - MAPPING_4_MEASUREMENT
      - MAPPING_4_FIELD
      - MAPPING_4_TYPE
      - MAPPING_5_TOPIC
      - MAPPING_5_MEASUREMENT
      - MAPPING_5_FIELD
      - MAPPING_5_TYPE
      - MAPPING_6_TOPIC
      - MAPPING_6_MEASUREMENT
      - MAPPING_6_FIELD
      - MAPPING_6_TYPE
      - MAPPING_7_TOPIC
      - MAPPING_7_MEASUREMENT
      - MAPPING_7_FIELD
      - MAPPING_7_TYPE
      - MAPPING_8_TOPIC
      - MAPPING_8_MEASUREMENT
      - MAPPING_8_FIELD
      - MAPPING_8_TYPE
      - MAPPING_9_TOPIC
      - MAPPING_9_MEASUREMENT
      - MAPPING_9_FIELD
      - MAPPING_9_TYPE
      - MAPPING_10_TOPIC
      - MAPPING_10_MEASUREMENT
      - MAPPING_10_FIELD
      - MAPPING_10_TYPE
      - MAPPING_11_TOPIC
      - MAPPING_11_MEASUREMENT
      - MAPPING_11_FIELD
      - MAPPING_11_TYPE
      - MAPPING_12_TOPIC
      - MAPPING_12_MEASUREMENT
      - MAPPING_12_FIELD
      - MAPPING_12_TYPE
      - MAPPING_13_TOPIC
      - MAPPING_13_MEASUREMENT
      - MAPPING_13_FIELD
      - MAPPING_13_TYPE
      - MAPPING_14_TOPIC
      - MAPPING_14_MEASUREMENT
      - MAPPING_14_FIELD
      - MAPPING_14_TYPE
      - MAPPING_15_TOPIC
      - MAPPING_15_MEASUREMENT
      - MAPPING_15_FIELD
      - MAPPING_15_TYPE
      - MAPPING_16_TOPIC
      - MAPPING_16_MEASUREMENT
      - MAPPING_16_FIELD
      - MAPPING_16_TYPE  
    restart: always

  #renault-collector:
  #  image: ghcr.io/solectrus/renault-collector:latest
  #  links:
  #    - influxdb
  #  depends_on:
  #    - influxdb
  #  environment:
  #    - RENAULT_EMAIL
  #    - RENAULT_PASSWORD
  #    - RENAULT_INTERVAL
  #    - RENAULT_MODEL
  #    - GIGYA_API_KEY
  #    - KAMEREON_API_KEY
  #    - INFLUX_HOST
  #    - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
  #    - INFLUX_ORG
  #    - INFLUX_BUCKET
  #  command: bundle exec app/main.rb
  #  restart: always

  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_INTERVAL
    restart: always
    
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:latest
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
    environment:
      - TZ
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_PORT
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL=redis://redis:6379/1
    links:
      - influxdb
      - redis
    depends_on:
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

    
  watchtower:
    image: containrrr/watchtower
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope solectrus --cleanup
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'
```

### Deine vollständige `.env`

```text
##################################################################
# Dashboard application (the main part)
#
# Domain name or IP address of your host
APP_HOST=localhost
#
# SSL redirect: Use "true" (which is the default) if you want to auto-redirect to https
FORCE_SSL=true
#
# Secret token to secure cookies, 128 chars long hexadecimal encoded string (don't use this example, make some random changes!)
# Currently there are no cookies in Soletrus, but this may change in the future
SECRET_KEY_BASE=XXX
#
# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2022-06-20
#
# Price you pay for 1kWH (in EUR)
# Can be changed later in the UI when logged in as administrator
ELECTRICITY_PRICE=0.29
#
# Price you get for 1kWH (in EUR)
# Can be changed later in the UI when logged in as administrator
FEED_IN_TARIFF=0.0623
#
# Password for the PostgreSQL database, used by the app to comunicate internally with the database
POSTGRES_PASSWORD=XXX
#
# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=XXX
#
# Frames einbetten
FRAME_ANCESTORS=*
# FRAME_ANCESTORS=http://192.168.178.65:8123
#
##################################################################
# Influx database settings
#
# Influx host (to access from SOLECTRUS dashboard and collectors)
INFLUX_HOST=influxdb
INFLUX_SCHEMA=http
INFLUX_PORT=8086
#
# Credentials for the Influx database
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=XXX
INFLUX_ADMIN_TOKEN=XXX
INFLUX_BUCKET=my-solectrus-bucket
INFLUX_MEASUREMENT=SENEC
INFLUX_SENSOR_HEATPUMP_POWER=SENEC:heatpump_power
INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_WALLBOX_POWER=SENEC:wallbox_charge_power
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_INVERTER_POWER_FORECAST=Forecast:watt
INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_CAR_BATTERY_SOC=SENEC:opel_soc
INFLUX_SENSOR_CUSTOM_POWER_01=SENEC:trockner
INFLUX_SENSOR_CUSTOM_POWER_02=SENEC:waschmaschine
INFLUX_SENSOR_CUSTOM_POWER_03=SENEC:gefrierschrank
INFLUX_SENSOR_CUSTOM_POWER_04=SENEC:itdach
INFLUX_SENSOR_CUSTOM_POWER_05=SENEC:kuehlschrank
INFLUX_SENSOR_CUSTOM_POWER_06=SENEC:spuelmaschine
INFLUX_SENSOR_CUSTOM_POWER_07=SENEC:fernseher
#
# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, it is recommended NOT to use the admin token here. Instead,
# create two separate tokens for writing and reading (via the InfluxDB frontend).
INFLUX_TOKEN_WRITE=XXX
INFLUX_TOKEN_READ=XXX
#
# Volume path for storing the Influx data
INFLUX_VOLUME_PATH=/volume1/docker/solectrus/influxdb


##################################################################
# REDIS settings
#
REDIS_VOLUME_PATH=/volume1/docker/solectrus/redis


##################################################################
# PostgreSQL database settings
#
DB_VOLUME_PATH=/volume1/docker/solectrus/postgresql


##################################################################
# SENEC Collector
#
# Change this to your own SENEC IP address!
# SENEC_HOST=192.168.178.79
# SENEC_INTERVAL=5

##################################################################
# Solar forecasting with https://forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate
#
# Latitude of the plant location
FORECAST_LATITUDE=53.13993374308242
#
# Longitude of the plant location
FORECAST_LONGITUDE=8.111947732204783
#
# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_DECLINATION=30
#
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
FORECAST_AZIMUTH=0
#
# Installed modules power in kilowatt peak (kWp)
FORECAST_KWP=9.72
#
# Update interval in seconds, 900s = 15 minutes, the public (and free) API allows a minimum of 900 seconds
FORECAST_INTERVAL=900

##################################################################
# Lock app with a password
LOCKUP_CODEWORD=XXX

##################################################################
# MQTT Collector

# MQTT Broker credentials
MQTT_HOST=192.168.178.26
MQTT_PORT=1883
MQTT_SSL=false
MQTT_USERNAME=XXX
MQTT_PASSWORD=XXX

# MQTT topics
MAPPING_0_TOPIC=evcc/site/pvPower
MAPPING_0_MEASUREMENT=SENEC
MAPPING_0_FIELD=inverter_power
MAPPING_0_TYPE=integer
MAPPING_1_TOPIC=evcc/site/homePower
MAPPING_1_MEASUREMENT=SENEC
MAPPING_1_FIELD=house_power
MAPPING_1_TYPE=integer
MAPPING_2_TOPIC=evcc/site/grid/power
MAPPING_2_MEASUREMENT_POSITIVE=SENEC
MAPPING_2_MEASUREMENT_NEGATIVE=SENEC
MAPPING_2_FIELD_POSITIVE=grid_power_plus
MAPPING_2_FIELD_NEGATIVE=grid_power_minus
MAPPING_2_TYPE=integer
MAPPING_3_TOPIC=evcc/site/batteryPower
MAPPING_3_MEASUREMENT_POSITIVE=SENEC
MAPPING_3_MEASUREMENT_NEGATIVE=SENEC
MAPPING_3_FIELD_POSITIVE=bat_power_minus
MAPPING_3_FIELD_NEGATIVE=bat_power_plus
MAPPING_3_TYPE=integer
MAPPING_4_TOPIC=evcc/site/batterySoc
MAPPING_4_MEASUREMENT=SENEC
MAPPING_4_FIELD=bat_fuel_charge
MAPPING_4_TYPE=float
MAPPING_5_TOPIC=evcc/loadpoints/1/chargePower
MAPPING_5_MEASUREMENT=SENEC
MAPPING_5_FIELD=wallbox_charge_power
MAPPING_5_TYPE=integer
MAPPING_6_TOPIC=hassio/heatpump/watt
MAPPING_6_MEASUREMENT=SENEC
MAPPING_6_FIELD=heatpump_power
MAPPING_6_TYPE=integer
MAPPING_7_TOPIC=hassio/senec/casetemp
MAPPING_7_MEASUREMENT=SENEC
MAPPING_7_FIELD=case_temp
MAPPING_7_TYPE=float
MAPPING_8_TOPIC=hassio/senec/systemstate
MAPPING_8_MEASUREMENT=SENEC
MAPPING_8_FIELD=current_state
MAPPING_8_TYPE=string
MAPPING_9_TOPIC=hassio/opel/soc
MAPPING_9_MEASUREMENT=SENEC
MAPPING_9_FIELD=opel_soc
MAPPING_9_TYPE=integer
MAPPING_10_TOPIC=hassio/trockner/watt
MAPPING_10_MEASUREMENT=SENEC
MAPPING_10_FIELD=trockner
MAPPING_10_TYPE=integer
MAPPING_11_TOPIC=hassio/waschmaschine/watt
MAPPING_11_MEASUREMENT=SENEC
MAPPING_11_FIELD=waschmaschine
MAPPING_11_TYPE=integer
MAPPING_12_TOPIC=hassio/gefrierschrank/watt
MAPPING_12_MEASUREMENT=SENEC
MAPPING_12_FIELD=gefrierschrank
MAPPING_12_TYPE=integer
MAPPING_13_TOPIC=hassio/itdach/watt
MAPPING_13_MEASUREMENT=SENEC
MAPPING_13_FIELD=itdach
MAPPING_13_TYPE=integer
MAPPING_14_TOPIC=hassio/kuehlschrank/watt
MAPPING_14_MEASUREMENT=SENEC
MAPPING_14_FIELD=kuehlschrank
MAPPING_14_TYPE=integer
MAPPING_15_TOPIC=hassio/spuelmaschine/watt
MAPPING_15_MEASUREMENT=SENEC
MAPPING_15_FIELD=spuelmaschine
MAPPING_15_TYPE=integer
MAPPING_16_TOPIC=hassio/fernseher/watt
MAPPING_16_MEASUREMENT=SENEC
MAPPING_16_FIELD=fernseher
MAPPING_16_TYPE=integer
```
